import { useMemo, useState } from 'react'

function N({label,value,setValue,unit}:{label:string,value:number,setValue:(v:number)=>void,unit:string}){return <label>{label} ({unit})<input type="number" step="0.1" value={value} onChange={e=>setValue(Number(e.target.value))}/></label>}
function Metric({name,value}:{name:string,value:string}){return <div className="metric"><span>{name}</span><strong>{value}</strong></div>}
function Sketch({kind}:{kind:'frame'|'truss'|'column'|'slab'|'footing'|'wall'}){return <svg viewBox="0 0 700 260" className="beamSvg" role="img" aria-label={kind}>
  {kind==='frame'&&<><line x1="150" y1="210" x2="150" y2="60" className="structLine"/><line x1="150" y1="60" x2="550" y2="60" className="structLine"/><line x1="550" y1="60" x2="550" y2="210" className="structLine"/><polygon points="130,225 170,225 150,210" className="support"/><polygon points="530,225 570,225 550,210" className="support"/></>}
  {kind==='truss'&&<><polyline points="90,205 210,75 350,205 490,75 610,205" className="structOpen"/><line x1="90" y1="205" x2="610" y2="205" className="structLine"/><line x1="210" y1="75" x2="490" y2="75" className="structLine"/><line x1="210" y1="75" x2="350" y2="205" className="structLine"/><line x1="350" y1="205" x2="490" y2="75" className="structLine"/></>}
  {kind==='column'&&<><rect x="305" y="45" width="90" height="165" className="structFill"/><line x1="350" y1="18" x2="350" y2="65" className="loadLine"/><polygon points="342,55 358,55 350,70" className="loadArrow"/></>}
  {kind==='slab'&&<><polygon points="130,85 500,55 575,165 205,195" className="structFill"/><line x1="130" y1="85" x2="205" y2="195" className="structLine"/></>}
  {kind==='footing'&&<><rect x="315" y="40" width="70" height="100" className="structFill"/><polygon points="190,140 510,140 570,210 130,210" className="structFill2"/></>}
  {kind==='wall'&&<><polygon points="280,45 350,45 350,205 230,205" className="structFill"/><polygon points="350,75 590,205 350,205" className="soilFill"/><line x1="470" y1="125" x2="365" y2="125" className="loadLine"/><polygon points="375,117 375,133 360,125" className="loadArrow"/></>}
</svg>}

export function FramesPage(){const [L,setL]=useState(6),[H,setH]=useState(3.2),[w,setW]=useState(15); const r=useMemo(()=>({total:w*L,each:w*L/2,beam:w*L*L/8}),[L,H,w]);return <Calc title="Pórticos" sub="Pórtico plano · estimativa preliminar" sketch="frame" fields={<><N label="Vão" value={L} setValue={setL} unit="m"/><N label="Altura" value={H} setValue={setH} unit="m"/><N label="Carga na travessa" value={w} setValue={setW} unit="kN/m"/></>} results={<><Metric name="Carga total" value={`${r.total.toFixed(2)} kN`}/><Metric name="Reação vertical/base" value={`${r.each.toFixed(2)} kN`}/><Metric name="M* de referência" value={`${r.beam.toFixed(2)} kN·m`}/></>}/>} 
export function TrussesPage(){const [L,setL]=useState(12),[P,setP]=useState(40),[n,setN]=useState(4);const panel=L/Math.max(1,n);return <Calc title="Treliças" sub="Geometria e ações nodais" sketch="truss" fields={<><N label="Vão" value={L} setValue={setL} unit="m"/><N label="Carga total" value={P} setValue={setP} unit="kN"/><N label="Painéis" value={n} setValue={setN} unit="un"/></>} results={<><Metric name="Comprimento/painel" value={`${panel.toFixed(2)} m`}/><Metric name="Reação simétrica" value={`${(P/2).toFixed(2)} kN`}/><Metric name="Carga/painel" value={`${(P/Math.max(1,n)).toFixed(2)} kN`}/></>}/>} 
export function ColumnsPage(){const [b,setB]=useState(.3),[h,setH]=useState(.3),[Ned,setN]=useState(800);const A=b*h;const sig=Ned/(A*1000);return <Calc title="Pilares" sub="Pré-dimensionamento de secção" sketch="column" fields={<><N label="b" value={b} setValue={setB} unit="m"/><N label="h" value={h} setValue={setH} unit="m"/><N label="NEd" value={Ned} setValue={setN} unit="kN"/></>} results={<><Metric name="Área" value={`${A.toFixed(3)} m²`}/><Metric name="Tensão média" value={`${sig.toFixed(2)} MPa`}/><Metric name="Raio de giração*" value={`${(Math.min(b,h)/Math.sqrt(12)).toFixed(3)} m`}/></>}/>} 
export function SlabsPage(){const [L,setL]=useState(4.5),[g,setG]=useState(5),[q,setQ]=useState(2);const w=1.35*g+1.5*q;return <Calc title="Lajes" sub="Faixa de 1,00 m · estimativa ELU" sketch="slab" fields={<><N label="Vão" value={L} setValue={setL} unit="m"/><N label="Gk" value={g} setValue={setG} unit="kN/m²"/><N label="Qk" value={q} setValue={setQ} unit="kN/m²"/></>} results={<><Metric name="wEd" value={`${w.toFixed(2)} kN/m²`}/><Metric name="MEd/faixa*" value={`${(w*L*L/8).toFixed(2)} kN·m/m`}/><Metric name="VEd/faixa*" value={`${(w*L/2).toFixed(2)} kN/m`}/></>}/>} 
export function FoundationsPage(){const [loadN,setLoadN]=useState(900),[qa,setQa]=useState(200),[ratio,setR]=useState(1);const A=loadN/qa;const B=Math.sqrt(A/Math.max(.2,ratio));const L=B*ratio;return <Calc title="Sapatas" sub="Área preliminar por tensão admissível" sketch="footing" fields={<><N label="Carga vertical" value={loadN} setValue={setLoadN} unit="kN"/><N label="q adm." value={qa} setValue={setQa} unit="kPa"/><N label="L/B" value={ratio} setValue={setR} unit="-"/></>} results={<><Metric name="Área necessária" value={`${A.toFixed(2)} m²`}/><Metric name="B estimado" value={`${B.toFixed(2)} m`}/><Metric name="L estimado" value={`${L.toFixed(2)} m`}/></>}/>} 
export function WallsPage(){const [H,setH]=useState(4),[gamma,setG]=useState(19),[phi,setPhi]=useState(30);const rad=phi*Math.PI/180,Ka=(1-Math.sin(rad))/(1+Math.sin(rad)),Pa=.5*Ka*gamma*H*H;return <Calc title="Muros" sub="Impulso ativo de terras · Rankine simplificado" sketch="wall" fields={<><N label="Altura" value={H} setValue={setH} unit="m"/><N label="γ solo" value={gamma} setValue={setG} unit="kN/m³"/><N label="φ'" value={phi} setValue={setPhi} unit="°"/></>} results={<><Metric name="Ka" value={Ka.toFixed(3)}/><Metric name="Pa" value={`${Pa.toFixed(2)} kN/m`}/><Metric name="Aplicação" value={`${(H/3).toFixed(2)} m da base`}/></>}/>} 
export function CombinationsPage(){const [G,setG]=useState(100),[Q,setQ]=useState(60);const elu=1.35*G+1.5*Q,els=G+Q;return <div className="page"><div className="pageTitle"><h1>Combinações</h1><span>EC0/EC1 · combinação básica simplificada</span></div><div className="workspace"><section className="panel"><div className="formGrid"><N label="Gk" value={G} setValue={setG} unit="kN"/><N label="Qk" value={Q} setValue={setQ} unit="kN"/></div></section><aside className="panel resultPanel"><div className="panelTitle">Resultados</div><Metric name="ELU" value={`${elu.toFixed(2)} kN`}/><Metric name="ELS característica" value={`${els.toFixed(2)} kN`}/><p className="note">Combinação preliminar com uma ação variável. Coeficientes ψ, situações acidentais e combinações completas serão acrescentados numa fase posterior.</p></aside></div></div>}
function Calc({title,sub,sketch,fields,results}:{title:string,sub:string,sketch:'frame'|'truss'|'column'|'slab'|'footing'|'wall',fields:React.ReactNode,results:React.ReactNode}){return <div className="page"><div className="pageTitle"><h1>{title}</h1><span>{sub}</span></div><div className="workspace"><section className="panel editorPanel"><Sketch kind={sketch}/><div className="formGrid">{fields}</div></section><aside className="panel resultPanel"><div className="panelTitle">Resultados</div>{results}<p className="note">* Resultado de pré-dimensionamento/estudo. Não substitui a verificação regulamentar completa nem projeto por técnico habilitado.</p></aside></div></div>}
