import React,{useMemo,useState} from 'react'
import {solveFixedPropped} from './solver'
const F=({l,v,s,u}:{l:string,v:number,s:(n:number)=>void,u?:string})=><label className="compact-field"><span>{l}</span><div><input type="number" step="any" value={v} onChange={e=>s(+e.target.value)}/>{u&&<em>{u}</em>}</div></label>
const R=({l,v}:{l:string,v:string})=><div className="result-line"><span>{l}</span><b>{v}</b></div>
export default function FixedProppedBeamPage(){
 const[L,setL]=useState(6),[q,setQ]=useState(10),[P,setP]=useState(20),[a,setA]=useState(3),[E,setE]=useState(30),[I,setI]=useState(.008333),[tab,setTab]=useState<'data'|'results'|'diagrams'|'checks'>('data')
 const r=useMemo(()=>solveFixedPropped({L,q,P,a,E,I}),[L,q,P,a,E,I])
 return <div className="beam-pro-page"><header className="beam-pro-header"><div><small>VIGA</small><h2>Encastrada — Apoiada</h2></div><div className="beam-actions"><button>Guardar</button><button>Relatório</button><button className="accent">Calcular</button></div></header>
 <nav className="beam-mobile-tabs">{([['data','Dados'],['results','Resultados'],['diagrams','Diagramas'],['checks','Verificações']] as const).map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav>
 <div className="beam-pro-grid"><main className={(tab==='data'||tab==='diagrams')?'mobile-show':''}><section className="tech-card"><h3>MODELO</h3><BeamModel L={L} q={q} P={P} a={a}/></section><section className="tech-card"><h3>DADOS</h3><div className="compact-fields"><F l="Comprimento L" v={L} s={setL} u="m"/><F l="Carga distribuída q" v={q} s={setQ} u="kN/m"/><F l="Carga pontual P" v={P} s={setP} u="kN"/><F l="Posição a" v={a} s={setA} u="m"/><F l="Módulo E" v={E} s={setE} u="GPa"/><F l="Inércia I" v={I} s={setI} u="m⁴"/></div></section></main>
 <aside className={(tab==='results'||tab==='diagrams'||tab==='checks')?'mobile-show':''}><section className="tech-card"><h3>RESULTADOS PRINCIPAIS</h3><R l="Reação A" v={`${r.RA.toFixed(2)} kN`}/><R l="Momento em A" v={`${r.MA.toFixed(2)} kN·m`}/><R l="Reação B" v={`${r.RB.toFixed(2)} kN`}/><R l="V máx." v={`${r.Vmax.toFixed(2)} kN`}/><R l="M máx." v={`${r.Mmax.toFixed(2)} kN·m`}/><R l="Flecha máx." v={`${(r.ymax*1000).toFixed(2)} mm`}/></section><section className="tech-card"><h3>DIAGRAMAS</h3><Diag pts={r.points} f="V"/><Diag pts={r.points} f="M"/><Defl pts={r.deflection}/></section></aside></div></div>}
function BeamModel({L,q,P,a}:{L:number,q:number,P:number,a:number}){const x1=65,x2=605,y=155,w=x2-x1,xp=x1+w*Math.max(0,Math.min(1,a/Math.max(L,.01)));return <svg viewBox="0 0 670 245" className="eng-svg"><line x1={x1} y1={y} x2={x2} y2={y} stroke="#d8e6f3" strokeWidth="8"/><rect x="42" y="100" width="14" height="112" fill="#8397aa"/><polygon points={`${x2},${y+5} ${x2-15},${y+30} ${x2+15},${y+30}`} fill="#62a8dd"/><circle cx={x2-8} cy={y+37} r="4" fill="#9ac7e7"/><circle cx={x2+8} cy={y+37} r="4" fill="#9ac7e7"/>{Array.from({length:12}).map((_,i)=>{const x=x1+i*w/11;return <g key={i}><line x1={x} y1="82" x2={x} y2="137" stroke="#24c8c2" strokeWidth="2"/><polygon points={`${x-5},130 ${x+5},130 ${x},141`} fill="#24c8c2"/></g>})}{P!==0&&<g><line x1={xp} y1="55" x2={xp} y2="135" stroke="#fff" strokeWidth="4"/><polygon points={`${xp-7},124 ${xp+7},124 ${xp},140`} fill="#fff"/></g>}<text x="280" y="225" fill="#a9bdd1">L = {L.toFixed(2)} m</text><text x="68" y="68" fill="#24c8c2">q = {q.toFixed(2)} kN/m</text></svg>}
function Diag({pts,f}:{pts:{x:number,V:number,M:number}[],f:'V'|'M'}){const W=520,H=150,p=25,L=pts.length ? pts[pts.length-1].x : 1,vals=pts.map(x=>x[f]),max=Math.max(1,...vals.map(Math.abs)),X=(x:number)=>p+(W-2*p)*x/L,Y=(v:number)=>H/2-v*(H*.34)/max,d=pts.map((pt,i)=>`${i?'L':'M'} ${X(pt.x)} ${Y(pt[f])}`).join(' ');return <svg viewBox={`0 0 ${W} ${H}`} className="mini-diagram"><line x1={p} y1={H/2} x2={W-p} y2={H/2} stroke="#38516a"/><path d={d} fill="none" stroke={f==='V'?'#56cf76':'#45aaf2'} strokeWidth="3"/></svg>}
function Defl({pts}:{pts:{x:number,y:number}[]}){const W=520,H=150,p=25,L=pts.length ? pts[pts.length-1].x : 1,max=Math.max(1e-9,...pts.map(x=>Math.abs(x.y))),X=(x:number)=>p+(W-2*p)*x/L,Y=(v:number)=>H/2-v*(H*.34)/max,d=pts.map((pt,i)=>`${i?'L':'M'} ${X(pt.x)} ${Y(pt.y)}`).join(' ');return <svg viewBox={`0 0 ${W} ${H}`} className="mini-diagram"><line x1={p} y1={H/2} x2={W-p} y2={H/2} stroke="#38516a"/><path d={d} fill="none" stroke="#f2a900" strokeWidth="3"/></svg>}
