import React,{useMemo,useState} from 'react'
import {solveColumn,type EndCondition} from './ColumnSolver'
import {fmt} from '../../engineering/structuralMath'
const F=({l,v,s,u}:{l:string,v:number,s:(n:number)=>void,u?:string})=><label className="field"><span>{l}{u?` (${u})`:''}</span><input type="number" step="any" value={v} onChange={e=>s(+e.target.value)}/></label>
export default function ColumnsProPage(){
 const[N,setN]=useState(900),[Mx,setMx]=useState(65),[My,setMy]=useState(20),[b,setB]=useState(.35),[h,setH]=useState(.45),[L,setL]=useState(3),[fck,setFck]=useState(30),[fyk,setFyk]=useState(500),[E,setE]=useState(30),[cover,setCover]=useState(.035),[phi,setPhi]=useState(16),[k,setK]=useState(1),[end,setEnd]=useState<EndCondition>('pinned')
 const r=useMemo(()=>solveColumn({N,Mx,My,b,h,L,fck,fyk,E,cover,phi,k,end}),[N,Mx,My,b,h,L,fck,fyk,E,cover,phi,k,end])
 return <div className="module-page"><div className="module-head"><div><h2>Pilares PRO · V55</h2><p>Compressão + flexão biaxial, comprimento efetivo, Euler, 2.ª ordem e armadura preliminar.</p></div></div>
 <div className="tabs-row">{(['pinned','fixed-pinned','fixed-fixed','cantilever','custom'] as EndCondition[]).map(x=><button key={x} className={end===x?'active':''} onClick={()=>setEnd(x)}>{({pinned:'Articulado-articulado','fixed-pinned':'Encastrado-articulado','fixed-fixed':'Bi-encastrado',cantilever:'Consola',custom:'k manual'} as any)[x]}</button>)}</div>
 <div className="work-grid"><section className="panel"><h3>Ações / geometria</h3><div className="form-grid"><F l="NEd" u="kN" v={N} s={setN}/><F l="Mx,Ed" u="kN·m" v={Mx} s={setMx}/><F l="My,Ed" u="kN·m" v={My} s={setMy}/><F l="b" u="m" v={b} s={setB}/><F l="h" u="m" v={h} s={setH}/><F l="Comprimento L" u="m" v={L} s={setL}/>{end==='custom'&&<F l="Coeficiente k" v={k} s={setK}/>}</div><h3>Material / armadura</h3><div className="form-grid"><F l="fck" u="MPa" v={fck} s={setFck}/><F l="fyk" u="MPa" v={fyk} s={setFyk}/><F l="E" u="GPa" v={E} s={setE}/><F l="Recobrimento" u="m" v={cover} s={setCover}/><F l="Ø longitudinal" u="mm" v={phi} s={setPhi}/></div></section>
 <section className="panel"><h3>Estabilidade</h3><div className="result-grid"><M t="k efetivo" v={fmt(r.kEff,2)}/><M t="L efetivo" v={`${fmt(r.le,2)} m`}/><M t="λx" v={fmt(r.lambdaX,1)}/><M t="λy" v={fmt(r.lambdaY,1)}/><M t="Ncr,x" v={`${fmt(r.NcrX,0)} kN`}/><M t="Ncr,y" v={`${fmt(r.NcrY,0)} kN`}/></div></section></div>
 <div className="result-grid"><M t="NEd/Ncr" v={fmt(r.eta,3)}/><M t="Amplificação 2ª ordem" v={fmt(r.amp,2)}/><M t="Mx,2" v={`${fmt(r.Mx2)} kN·m`}/><M t="My,2" v={`${fmt(r.My2)} kN·m`}/><M t="σ máx." v={`${fmt(r.sigMax)} MPa`}/></div>
 <section className="panel"><h3>Armadura preliminar</h3><div className="result-grid"><M t="As mínima" v={`${fmt(r.AsMin,0)} mm²`}/><M t="As requerida" v={`${fmt(r.AsReq,0)} mm²`}/><M t="Proposta" v={`${r.nBars} Ø${phi}`}/><M t="As fornecida" v={`${fmt(r.AsProv,0)} mm²`}/><M t="Interação N-Mx-My" v={fmt(r.interaction,2)}/></div><p className="note">2.ª ordem por amplificação elástica baseada em Ncr de Euler. Para estudo/pré-dimensionamento; confirmar imperfeições, fluência e EC2 completo no projeto.</p></section></div>}
const M=({t,v}:{t:string,v:string})=><div className="metric"><span>{t}</span><b>{v}</b></div>