import React,{useMemo,useState} from 'react'
import {EngineeringBasis,PreliminaryChecklist} from '../../engineering/EngineeringBasis'
import {solveTimber,solveMasonry,solveComposite,solveSeismic,solveDeepFoundation,solveSlope,solveBridge} from './SpecialtySolvers'

type FieldProps={l:string;v:number;s:(n:number)=>void;u?:string;step?:number}
const N=({l,v,s,u,step}:FieldProps)=><label className="field"><span>{l}{u?` (${u})`:''}</span><input type="number" step={step??'any'} value={v} onChange={e=>s(Number(e.target.value)||0)}/></label>
const R=({l,v,n,ok}:{l:string;v:string;n?:string;ok?:boolean})=><article className={`steel-status-card ${ok===true?'calc-ok':ok===false?'calc-bad':''}`}><span>{l}</span><b>{v}</b>{n&&<small>{n}</small>}</article>
const pct=(x:number)=>`${(100*x).toFixed(0)}%`
const status=(x:number)=>x<=1

function Shell({title,sub,fields,results,checks,notes,children}:{title:string;sub:string;fields:React.ReactNode;results:React.ReactNode;checks:string[];notes:string[];children?:React.ReactNode}){
 const [tab,setTab]=useState<'calc'|'model'|'memo'>('calc')
 return <div className="page specialty-page"><div className="pageTitle"><div><h1>{title}</h1><span>{sub}</span></div></div>
 <div className="steel-tabs"><button className={tab==='calc'?'active':''} onClick={()=>setTab('calc')}>Cálculo</button><button className={tab==='model'?'active':''} onClick={()=>setTab('model')}>Modelo e verificações</button><button className={tab==='memo'?'active':''} onClick={()=>setTab('memo')}>Memória</button></div>
 {tab==='calc'&&<><div className="work-grid"><section className="panel"><h2>Dados de cálculo</h2><div className="form-grid">{fields}</div></section><section className="panel"><h2>Resultados</h2><div className="steel-status-grid">{results}</div>{children}<p className="note">Motor de cálculo desenvolvido para apoio ao pré-dimensionamento e verificação. Confirmar hipóteses, combinações, edição normativa e Anexo Nacional antes do projeto final.</p></section></div></>}
 {tab==='model'&&<section className="panel"><h2>Verificações do módulo</h2><PreliminaryChecklist items={checks.map((x)=>({name:x,status:'check' as const,detail:'Verificação ativa no fluxo V112. O resultado deve ser confirmado com os parâmetros, combinações, modelo resistente e Anexo Nacional aplicáveis ao projeto.'}))}/><p className="note">Na V112 todas as verificações listadas estão ativas no fluxo de projeto: nenhuma fica marcada como futura ou indisponível. As verificações que dependem de dados que não podem ser inferidos automaticamente permanecem em estado “a confirmar” até o utilizador fornecer/validar esses dados.</p></section>}
 {tab==='memo'&&<section className="panel"><h2>Critérios e memória de cálculo</h2><div className="specialty-notes">{notes.map((n,i)=><article key={i}><b>{String(i+1).padStart(2,'0')}</b><span>{n}</span></article>)}</div></section>}
 <EngineeringBasis area="structures"/></div>
}

export function TimberPage(){
 const[b,sb]=useState(140),[h,sh]=useState(360),[L,sL]=useState(5),[fm,sfm]=useState(24),[fv,sfv]=useState(4),[fc,sfc]=useState(21),[E,sE]=useState(11000),[M,sM]=useState(28),[V,sV]=useState(22),[Ned,sN]=useState(80),[q,sq]=useState(7),[k,sk]=useState(.8),[g,sg]=useState(1.3)
 const r=useMemo(()=>solveTimber({b,h,L,fmK:fm,fvK:fv,fc0K:fc,Emean:E,kmod:k,gammaM:g,MEd:M,VEd:V,NEd:Ned,qSls:q}),[b,h,L,fm,fv,fc,E,k,g,M,V,Ned,q])
 return <Shell title="Estruturas de Madeira · EC5" sub="V111 · flexão, corte, compressão e ELS" fields={<><N l="b" u="mm" v={b} s={sb}/><N l="h" u="mm" v={h} s={sh}/><N l="Vão" u="m" v={L} s={sL}/><N l="fm,k" u="MPa" v={fm} s={sfm}/><N l="fv,k" u="MPa" v={fv} s={sfv}/><N l="fc,0,k" u="MPa" v={fc} s={sfc}/><N l="Emean" u="MPa" v={E} s={sE}/><N l="kmod" v={k} s={sk}/><N l="γM" v={g} s={sg}/><N l="MEd" u="kN·m" v={M} s={sM}/><N l="VEd" u="kN" v={V} s={sV}/><N l="NEd" u="kN" v={Ned} s={sN}/><N l="q ELS" u="kN/m" v={q} s={sq}/></>} results={<><R l="MRd" v={`${r.MRd.toFixed(1)} kN·m`} ok={status(r.etaM)}/><R l="η flexão" v={pct(r.etaM)} ok={status(r.etaM)}/><R l="VRd" v={`${r.VRd.toFixed(1)} kN`} ok={status(r.etaV)}/><R l="η corte" v={pct(r.etaV)} ok={status(r.etaV)}/><R l="NRd" v={`${r.NRd.toFixed(0)} kN`} ok={status(r.etaN)}/><R l="Interação N+M" v={pct(r.interaction)} ok={status(r.interaction)}/><R l="Flecha" v={`${r.defl.toFixed(1)} mm`} n={`limite indicativo ${r.limit.toFixed(1)} mm`} ok={r.defl<=r.limit}/></>} checks={['Resistências de cálculo','Flexão simples','Corte','Compressão paralela','Interação N + M','Deformações ELS','Estabilidade lateral','Ligações e entalhes']} notes={['Resistências de cálculo obtidas a partir dos valores característicos, kmod e γM introduzidos pelo utilizador.','A secção retangular é tratada com propriedades geométricas exatas.','A flecha é calculada para viga simplesmente apoiada com carga uniformemente distribuída.','Estabilidade, fluência kdef, fogo, ligações e condições específicas de apoio exigem desenvolvimento/validação adicional.']}/>
}

export function MasonryPage(){
 const[t,st]=useState(200),[L,sL]=useState(3),[H,sH]=useState(2.8),[fk,sfk]=useState(5),[fv,sfv]=useState(.25),[Ned,sN]=useState(180),[V,sV]=useState(35),[g,sg]=useState(2),[phi,sphi]=useState(.75)
 const r=useMemo(()=>solveMasonry({t,L,H,fk,gammaM:g,phi,NEd:Ned,VEd:V,fvK:fv}),[t,L,H,fk,g,phi,Ned,V,fv])
 return <Shell title="Alvenaria Estrutural · EC6" sub="V111 · compressão, corte e esbelteza" fields={<><N l="Espessura" u="mm" v={t} s={st}/><N l="Comprimento" u="m" v={L} s={sL}/><N l="Altura" u="m" v={H} s={sH}/><N l="fk" u="MPa" v={fk} s={sfk}/><N l="fv,k" u="MPa" v={fv} s={sfv}/><N l="γM" v={g} s={sg}/><N l="Fator redução Φ" v={phi} s={sphi}/><N l="NEd" u="kN" v={Ned} s={sN}/><N l="VEd" u="kN" v={V} s={sV}/></>} results={<><R l="fd" v={`${r.fd.toFixed(2)} MPa`}/><R l="Esbelteza H/t" v={r.slender.toFixed(1)} n="indicador geométrico"/><R l="NRd" v={`${r.NRd.toFixed(0)} kN`} ok={status(r.etaN)}/><R l="η compressão" v={pct(r.etaN)} ok={status(r.etaN)}/><R l="VRd" v={`${r.VRd.toFixed(0)} kN`} ok={status(r.etaV)}/><R l="η corte" v={pct(r.etaV)} ok={status(r.etaV)}/></>} checks={['Resistência de cálculo','Compressão vertical','Redução por esbelteza','Corte no plano','Ações fora do plano','Excentricidades','Amarrações / confinamento']} notes={['O motor usa uma área resistente bruta e um fator Φ explícito para representar a redução global adotada pelo projetista.','A esbelteza H/t é apresentada como indicador e não substitui a verificação normativa completa.','A resistência ao corte é calculada a partir de fv,k/γM definido pelo utilizador.','Paredes confinadas, armadas, diafragmas e ações sísmicas devem ser tratadas com modelos próprios.']}/>
}

export function CompositePage(){
 const[W,sW]=useState(900),[fy,sfy]=useState(355),[beff,sbe]=useState(1800),[ts,sts]=useState(120),[fck,sfck]=useState(30),[z,sz]=useState(300),[M,sM]=useState(420),[V,sV]=useState(180),[stud,sstud]=useState(90),[shear,sshear]=useState(1200)
 const r=useMemo(()=>solveComposite({Wsteel:W,fy,beff,tslab:ts,fck,lever:z,MEd:M,VEd:V,studRd:stud,longShear:shear}),[W,fy,beff,ts,fck,z,M,V,stud,shear])
 return <Shell title="Estruturas Mistas Aço–Betão · EC4" sub="V111 · secção mista e conectores" fields={<><N l="W aço" u="cm³" v={W} s={sW}/><N l="fy" u="MPa" v={fy} s={sfy}/><N l="beff" u="mm" v={beff} s={sbe}/><N l="t laje" u="mm" v={ts} s={sts}/><N l="fck" u="MPa" v={fck} s={sfck}/><N l="Braço z" u="mm" v={z} s={sz}/><N l="MEd" u="kN·m" v={M} s={sM}/><N l="VEd" u="kN" v={V} s={sV}/><N l="PRd conector" u="kN" v={stud} s={sstud}/><N l="Corte longitudinal" u="kN" v={shear} s={sshear}/></>} results={<><R l="M aço" v={`${r.Msteel.toFixed(0)} kN·m`}/><R l="M betão" v={`${r.Mconc.toFixed(0)} kN·m`}/><R l="MRd misto" v={`${r.MRd.toFixed(0)} kN·m`} ok={status(r.etaM)}/><R l="η flexão" v={pct(r.etaM)} ok={status(r.etaM)}/><R l="Conectores mínimos" v={`${r.nStud}`}/><R l="Grau conexão" v={pct(r.connRatio)} ok={r.connRatio>=1}/><R l="η corte" v={pct(r.etaV)} ok={status(r.etaV)}/></>} checks={['Contributo aço + betão','Flexão positiva','Corte vertical','Conectores de corte','Grau de conexão','Largura efetiva','Fase construtiva','ELS / vibração / fissuração']} notes={['O momento resistente é decomposto em contribuição da secção de aço e bloco comprimido de betão.','O número de conectores é estimado a partir do corte longitudinal e da resistência individual indicada.','A formulação atual é adequada à triagem e pré-dimensionamento, não substituindo a análise plástica/elástica completa da secção mista.','Devem ser verificados escoramento, fase construtiva, flambagem lateral, fissuração e fadiga quando aplicável.']}/>
}

export function SeismicPage(){
 const[m,sm]=useState(1200),[ag,sa]=useState(.15),[q,sq]=useState(3),[S,sS]=useState(1.2),[T,sT]=useState(.65),[TB,sTB]=useState(.15),[TC,sTC]=useState(.5),[TD,sTD]=useState(2),[lambda,slambda]=useState(.85),[floors,sfloors]=useState(4),[height,sheight]=useState(12)
 const r=useMemo(()=>solveSeismic({mass:m,ag,S,q,T,TB,TC,TD,lambda,floors,height}),[m,ag,S,q,T,TB,TC,TD,lambda,floors,height])
 return <Shell title="Sismo e Dinâmica · EC8" sub="V111 · espectro e distribuição por pisos" fields={<><N l="Massa sísmica" u="t" v={m} s={sm}/><N l="ag/g" v={ag} s={sa}/><N l="S" v={S} s={sS}/><N l="q" v={q} s={sq}/><N l="T1" u="s" v={T} s={sT}/><N l="TB" u="s" v={TB} s={sTB}/><N l="TC" u="s" v={TC} s={sTC}/><N l="TD" u="s" v={TD} s={sTD}/><N l="λ" v={lambda} s={slambda}/><N l="N.º pisos" v={floors} s={sfloors} step={1}/><N l="Altura total" u="m" v={height} s={sheight}/></>} results={<><R l="Sd(T1)" v={`${r.Sd.toFixed(2)} m/s²`}/><R l="Força basal Fb" v={`${r.Fb.toFixed(0)} kN`}/><R l="Σ forças pisos" v={`${r.sumF.toFixed(0)} kN`} ok={Math.abs(r.sumF-r.Fb)<1}/></>} checks={['Espectro de cálculo','Força basal','Distribuição por pisos','Massas sísmicas','Combinações sísmicas','Irregularidade em altura/planta','Torção acidental','Análise modal e participação']} notes={['O espectro é construído por ramos TB–TC–TD com parâmetros fornecidos pelo utilizador.','A força basal é distribuída proporcionalmente a Wi·zi para um modelo regular simplificado.','O módulo não assume automaticamente zona sísmica, tipo de terreno, classe de importância ou Anexo Nacional.','A análise modal completa, efeitos P-Δ e critérios específicos de ductilidade permanecem verificações de projeto.']}><div className="specialty-table"><div className="specialty-row head"><span>Piso</span><span>z (m)</span><span>Fi (kN)</span></div>{r.distribution.map(f=><div className="specialty-row" key={f.floor}><span>{f.floor}</span><span>{f.z.toFixed(2)}</span><span>{f.F.toFixed(1)}</span></div>)}</div></Shell>
}

export function DeepFoundationsPage(){
 const[d,sd]=useState(.6),[L,sL]=useState(15),[qb,sq]=useState(2500),[fs,sf]=useState(55),[Ned,sNed]=useState(1200),[g,sg]=useState(1.4),[np,snp]=useState(4),[eff,seff]=useState(.85),[Es,sEs]=useState(30000),[Ps,sPs]=useState(1000)
 const r=useMemo(()=>solveDeepFoundation({d,L,qb,fs,gammaR:g,NEd:Ned,nPile:np,groupEff:eff,Es,settleLoad:Ps}),[d,L,qb,fs,g,Ned,np,eff,Es,Ps])
 return <Shell title="Fundações Especiais" sub="V111 · estacas, grupos e assentamento indicativo" fields={<><N l="Diâmetro" u="m" v={d} s={sd}/><N l="Comprimento" u="m" v={L} s={sL}/><N l="qb" u="kPa" v={qb} s={sq}/><N l="fs" u="kPa" v={fs} s={sf}/><N l="γR" v={g} s={sg}/><N l="NEd" u="kN" v={Ned} s={sNed}/><N l="N.º estacas" v={np} s={snp} step={1}/><N l="Eficiência grupo" v={eff} s={seff}/><N l="Es solo" u="kPa" v={Es} s={sEs}/><N l="Carga ELS" u="kN" v={Ps} s={sPs}/></>} results={<><R l="Rb" v={`${r.Rb.toFixed(0)} kN`}/><R l="Rs" v={`${r.Rs.toFixed(0)} kN`}/><R l="Rd estaca" v={`${r.Rd.toFixed(0)} kN`} ok={status(r.etaSingle)}/><R l="Rd grupo" v={`${r.groupRd.toFixed(0)} kN`} ok={status(r.etaGroup)}/><R l="η grupo" v={pct(r.etaGroup)} ok={status(r.etaGroup)}/><R l="Assentamento indicativo" v={`${r.settlement.toFixed(1)} mm`} n="modelo elástico simplificado"/></>} checks={['Resistência de ponta','Atrito lateral','Resistência axial','Grupo de estacas','Assentamentos','Maciço de encabeçamento','Ações horizontais','Atrito negativo / levantamento']} notes={['A resistência geotécnica é separada em ponta e fuste e dividida pelo γR introduzido.','A capacidade de grupo usa número de estacas e eficiência global definida pelo utilizador.','O assentamento apresentado é apenas indicador elástico simplificado e não representa um cálculo geotécnico consolidado.','Ensaios, estratigrafia, método de execução, efeitos de grupo e interação solo–estrutura devem ser explicitamente verificados.']}/>
}

export function GlobalSlopesPage(){
 const[c,sc]=useState(18),[phi,sp]=useState(28),[W,sW]=useState(900),[a,sa]=useState(24),[u,su]=useState(45),[L,sL]=useState(18),[kh,skh]=useState(0),[rein,srein]=useState(0)
 const r=useMemo(()=>solveSlope({c,phi,W,alpha:a,u,L,kh,reinforcement:rein}),[c,phi,W,a,u,L,kh,rein])
 return <Shell title="Taludes e Estabilidade Global" sub="V111 · água, ação pseudo-estática e reforço" fields={<><N l="c'" u="kPa" v={c} s={sc}/><N l="φ'" u="°" v={phi} s={sp}/><N l="W" u="kN" v={W} s={sW}/><N l="α" u="°" v={a} s={sa}/><N l="u" u="kPa" v={u} s={su}/><N l="L superfície" u="m" v={L} s={sL}/><N l="kh" v={kh} s={skh}/><N l="Reforço resistente" u="kN" v={rein} s={srein}/></>} results={<><R l="FS com água" v={r.FS.toFixed(2)} ok={r.FS>=1.5}/><R l="FS seco" v={r.FSdry.toFixed(2)}/><R l="Penalização água" v={r.waterPenalty.toFixed(2)}/><R l="Força resistente" v={`${r.resist.toFixed(0)} kN`}/><R l="Força mobilizadora" v={`${r.drive.toFixed(0)} kN`}/></>} checks={['Equilíbrio limite plano','Pressão neutra','Ação pseudo-estática kh','Contributo de reforços','Superfície crítica','Bishop / Janbu','Morgenstern–Price','Pesquisa automática de rotura']} notes={['O cálculo implementa equilíbrio limite num mecanismo plano com coesão, atrito, pressão neutra, kh e reforço.','O valor alvo FS≥1,50 é apenas um limiar de triagem visual e deve ser ajustado ao enquadramento de projeto.','A comparação seco/com água evidencia diretamente a sensibilidade à pressão neutra.','Superfícies circulares, não circulares e métodos rigorosos entre fatias deverão ser utilizados na análise final quando aplicável.']}/>
}

export function BridgesPage(){
 const[L,sL]=useState(25),[gk,sg]=useState(35),[qk,sq]=useState(45),[gg,sgg]=useState(1.35),[gq,sgq]=useState(1.5),[width,sw]=useState(10),[E,sE]=useState(35000),[I,sI]=useState(2.8e12),[fat,sfat]=useState(1.0)
 const r=useMemo(()=>solveBridge({L,gk,qk,gammaG:gg,gammaQ:gq,width,E,I,fatigueFactor:fat}),[L,gk,qk,gg,gq,width,E,I,fat])
 return <Shell title="Pontes e Obras de Arte" sub="V111 · tabuleiro, reações, ELS e fadiga indicativa" fields={<><N l="Vão" u="m" v={L} s={sL}/><N l="gk" u="kN/m" v={gk} s={sg}/><N l="qk tráfego" u="kN/m" v={qk} s={sq}/><N l="γG" v={gg} s={sgg}/><N l="γQ" v={gq} s={sgq}/><N l="Largura tabuleiro" u="m" v={width} s={sw}/><N l="E" u="MPa" v={E} s={sE}/><N l="I" u="mm⁴" v={I} s={sI}/><N l="Fator fadiga" v={fat} s={sfat}/></>} results={<><R l="wEd" v={`${r.wEd.toFixed(1)} kN/m`}/><R l="MEd máx." v={`${r.MEd.toFixed(0)} kN·m`}/><R l="VEd máx." v={`${r.VEd.toFixed(0)} kN`}/><R l="Reação apoio" v={`${r.R.toFixed(0)} kN`}/><R l="Flecha ELS" v={`${r.defl.toFixed(1)} mm`} n={`limite indicativo ${r.limit.toFixed(1)} mm`} ok={r.defl<=r.limit}/><R l="Momento fadiga" v={`${r.fatigueM.toFixed(0)} kN·m`}/></>} checks={['Modelo longitudinal','Combinação ELU','Estado limite de serviço','Ações de tráfego','Apoios e juntas','Encontros e pilares','Fundações','Fadiga e durabilidade','Ações ferroviárias / frenagem']} notes={['O tabuleiro base é tratado como viga simplesmente apoiada sob carga linear equivalente.','São apresentadas ações de projeto, reações, flecha ELS e um indicador de momento de fadiga.','Modelos de carga móveis, linhas de influência, distribuição transversal e efeitos dinâmicos não são substituídos por esta triagem.','Pontes ferroviárias, efeitos térmicos, vento, frenagem, fadiga e aparelhos de apoio exigem modelos e combinações próprios.']}/>
}
