import React,{useMemo,useState} from 'react'
import {EngineeringBasis} from '../../engineering/EngineeringBasis'
import {isolatedFootingPro,stripFooting,raftFoundation,pileGroup} from './FoundationsSolver'
import {chooseDistributed,anchorageLength} from '../beamsPro/ReinforcementLibrary'
const F=({l,v,s,u}:{l:string,v:number,s:(n:number)=>void,u?:string})=><label className="field"><span>{l}{u?` (${u})`:''}</span><input type="number" step="any" value={v} onChange={e=>s(+e.target.value)}/></label>
const M=({t,v}:{t:string,v:string})=><div className="metric"><span>{t}</span><b>{v}</b></div>
export default function FoundationsProPage(){
 const[tab,setTab]=useState<'isolated'|'strip'|'raft'|'piles'>('isolated'),[N,setN]=useState(900),[Hx,setHx]=useState(40),[Hy,setHy]=useState(0),[Mx,setMx]=useState(50),[My,setMy]=useState(20),[B,setB]=useState(2.2),[L,setL]=useState(2.6),[h,setH]=useState(.55),[qAllow,setQ]=useState(250),[mu,setMu]=useState(.5),[cb,setCb]=useState(.4),[cl,setCl]=useState(.4),[cover,setC]=useState(.05),[fck,setFck]=useState(30),[fyk,setFyk]=useState(500),[phi,setPhi]=useState(12),[area,setArea]=useState(120),[nPiles,setNP]=useState(4),[capPile,setCap]=useState(450),[eff,setEff]=useState(.9)
 const iso=useMemo(()=>isolatedFootingPro({N,Hx,Hy,Mx,My,B,L,h,cb,cl,cover,qAllow,mu,fck,fyk,phi}),[N,Hx,Hy,Mx,My,B,L,h,cb,cl,cover,qAllow,mu,fck,fyk,phi]),st=useMemo(()=>stripFooting(N,B,qAllow),[N,B,qAllow]),ra=useMemo(()=>raftFoundation(N,area,qAllow),[N,area,qAllow]),pg=useMemo(()=>pileGroup(N,nPiles,capPile,eff),[N,nPiles,capPile,eff])
 const footingArm=useMemo(()=>({x:chooseDistributed(iso.Asx,250,8,25),y:chooseDistributed(iso.Asy,250,8,25)}),[iso.Asx,iso.Asy])
 const footingAnch=useMemo(()=>({x:anchorageLength(footingArm.x.dia,fck,fyk),y:anchorageLength(footingArm.y.dia,fck,fyk)}),[footingArm.x.dia,footingArm.y.dia,fck,fyk])
 return <div className="module-page"><div className="module-head"><div><h2>Fundações PRO</h2><p>Sapatas isoladas com excentricidade, contacto, estabilidade, punçoamento e armadura preliminar.</p></div></div>
 <div className="tabs-row">{[['isolated','Sapata isolada PRO'],['strip','Sapata corrida'],['raft','Radier'],['piles','Estacas']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k as any)}>{l}</button>)}</div>
 {tab==='isolated'?<><div className="work-grid"><section className="panel"><h3>Esforços do pilar</h3><div className="form-grid"><F l="NEd" u="kN" v={N} s={setN}/><F l="Hx" u="kN" v={Hx} s={setHx}/><F l="Hy" u="kN" v={Hy} s={setHy}/><F l="Mx" u="kN·m" v={Mx} s={setMx}/><F l="My" u="kN·m" v={My} s={setMy}/></div><h3>Sapata / terreno</h3><div className="form-grid"><F l="B" u="m" v={B} s={setB}/><F l="L" u="m" v={L} s={setL}/><F l="h" u="m" v={h} s={setH}/><F l="b pilar" u="m" v={cb} s={setCb}/><F l="l pilar" u="m" v={cl} s={setCl}/><F l="qadm" u="kPa" v={qAllow} s={setQ}/><F l="μ base/solo" v={mu} s={setMu}/></div></section>
 <section className="panel"><h3>Planta</h3><FootingSvg B={B} L={L} cb={cb} cl={cl} qmin={iso.qmin} qmax={iso.qmax}/><div className="form-grid"><F l="fck" u="MPa" v={fck} s={setFck}/><F l="fyk" u="MPa" v={fyk} s={setFyk}/><F l="Recobrimento" u="m" v={cover} s={setC}/><F l="Ø armadura" u="mm" v={phi} s={setPhi}/></div></section></div>
 <div className="result-grid"><M t="Peso sapata" v={`${iso.W.toFixed(1)} kN`}/><M t="ex" v={`${iso.ex.toFixed(3)} m`}/><M t="ey" v={`${iso.ey.toFixed(3)} m`}/><M t="q mín." v={`${iso.qmin.toFixed(1)} kPa`}/><M t="q máx." v={`${iso.qmax.toFixed(1)} kPa`}/><M t="Util. terreno" v={`${(100*iso.bearingUtil).toFixed(0)}%`}/></div>
 <section className="panel"><h3>Estabilidade</h3><div className="result-grid"><M t="Núcleo central X" v={iso.kx?'OK':'FORA'}/><M t="Núcleo central Y" v={iso.ky?'OK':'FORA'}/><M t="FS deslizamento" v={iso.slideFS.toFixed(2)}/><M t="FS derrubamento" v={iso.overturnFS.toFixed(2)}/><M t="Contacto integral" v={iso.qmin>=0?'SIM':'NÃO'}/><M t="Estado global" v={iso.ok?'OK':'REVER'}/></div></section>
 <section className="panel"><h3>Punçoamento / dimensionamento de armaduras</h3><div className="result-grid"><M t="d" v={`${(iso.d*1000).toFixed(0)} mm`}/><M t="vEd punç." v={`${iso.vEd.toFixed(3)} MPa`}/><M t="vRd,c prelim." v={`${iso.vRd.toFixed(3)} MPa`}/><M t="Punçoamento" v={iso.punchOK?'OK':'REVER'}/><M t="As X necessária" v={`${iso.Asx.toFixed(0)} mm²/m`}/><M t="Armadura X" v={footingArm.x.label}/><M t="As X colocada" v={`${footingArm.x.areaPerM.toFixed(0)} mm²/m`}/><M t="As Y necessária" v={`${iso.Asy.toFixed(0)} mm²/m`}/><M t="Armadura Y" v={footingArm.y.label}/><M t="As Y colocada" v={`${footingArm.y.areaPerM.toFixed(0)} mm²/m`}/></div><FootingRebarSvg B={B} L={L} cb={cb} cl={cl} xArm={footingArm.x} yArm={footingArm.y}/><div className="result-grid"><M t={`lb,d X Ø${footingArm.x.dia}`} v={`${footingAnch.x.lbd.toFixed(0)} mm`}/><M t={`lb,d Y Ø${footingArm.y.dia}`} v={`${footingAnch.y.lbd.toFixed(0)} mm`}/><M t={`Emenda X Ø${footingArm.x.dia}`} v={`${footingAnch.x.lap.toFixed(0)} mm`}/><M t={`Emenda Y Ø${footingArm.y.dia}`} v={`${footingAnch.y.lap.toFixed(0)} mm`}/></div><p className="note">Armadura inferior X/Y selecionada automaticamente. Confirmar EC2/EC7, combinações de ações, capacidade geotécnica e assentamentos, corte unidirecional, punçoamento, ancoragens, comprimentos de amarração e disposições construtivas antes do projeto de execução.</p></section></>
 :<div className="work-grid"><section className="panel"><h3>Dados</h3><div className="form-grid"><F l="NEd" u="kN" v={N} s={setN}/>{tab==='strip'&&<><F l="B" u="m" v={B} s={setB}/><F l="qadm" u="kPa" v={qAllow} s={setQ}/></>}{tab==='raft'&&<><F l="Área" u="m²" v={area} s={setArea}/><F l="qadm" u="kPa" v={qAllow} s={setQ}/></>}{tab==='piles'&&<><F l="N.º estacas" v={nPiles} s={setNP}/><F l="Cap./estaca" u="kN" v={capPile} s={setCap}/><F l="Eficiência" v={eff} s={setEff}/></>}</div></section><section className="panel"><h3>Resultados</h3><div className="result-grid">{tab==='strip'&&<><M t="q" v={`${st.q.toFixed(1)} kPa`}/><M t="Utilização" v={st.util.toFixed(2)}/></>}{tab==='raft'&&<><M t="q" v={`${ra.q.toFixed(1)} kPa`}/><M t="Utilização" v={ra.util.toFixed(2)}/></>}{tab==='piles'&&<><M t="Cap. grupo" v={`${pg.cap.toFixed(0)} kN`}/><M t="Utilização" v={pg.util.toFixed(2)}/></>}</div></section></div>}</div>}
function FootingSvg({B,L,cb,cl,qmin,qmax}:{B:number,L:number,cb:number,cl:number,qmin:number,qmax:number}){const W=480,H=320,s=Math.min(300/Math.max(B,.1),220/Math.max(L,.1)),bw=B*s,lw=L*s,x=(W-bw)/2,y=(H-lw)/2,cw=cb*s,ch=cl*s;return <svg viewBox={`0 0 ${W} ${H}`} className="eng-svg"><rect x={x} y={y} width={bw} height={lw} fill="#42566d" stroke="#9fb3c8" strokeWidth="3"/><rect x={(W-cw)/2} y={(H-ch)/2} width={cw} height={ch} fill="#758ba3"/><line x1={x} y1={y+lw+20} x2={x+bw} y2={y+lw+20} stroke="#42d4cd"/><text x={W/2-35} y={y+lw+42} fill="#9fb3c8">B={B.toFixed(2)} m</text><text x="15" y="25" fill="#9fb3c8">qmin {qmin.toFixed(0)} / qmax {qmax.toFixed(0)} kPa</text></svg>}
function FootingRebarSvg({B,L,cb,cl,xArm,yArm}:{B:number;L:number;cb:number;cl:number;xArm:{dia:number;spacing:number};yArm:{dia:number;spacing:number}}){
 const W=500,H=340,s=Math.min(360/Math.max(B,.1),240/Math.max(L,.1)),bw=B*s,lh=L*s,x=(W-bw)/2,y=(H-lh)/2,cw=cb*s,ch=cl*s
 return <div className="beam-section-wrap"><h4>Armadura inferior proposta</h4><svg viewBox={`0 0 ${W} ${H}`} className="eng-svg beam-section-svg">
  <rect x={x} y={y} width={bw} height={lh} fill="#42566d" opacity=".35" stroke="#9fb3c8" strokeWidth="3"/>
  {Array.from({length:10}).map((_,i)=><line key={'vx'+i} x1={x+15+i*(bw-30)/9} y1={y+10} x2={x+15+i*(bw-30)/9} y2={y+lh-10} stroke="#d7a85e" strokeWidth="2"/>)}
  {Array.from({length:7}).map((_,i)=><line key={'hy'+i} x1={x+10} y1={y+15+i*(lh-30)/6} x2={x+bw-10} y2={y+15+i*(lh-30)/6} stroke="#42d4cd" strokeWidth="2"/>)}
  <rect x={(W-cw)/2} y={(H-ch)/2} width={cw} height={ch} fill="#758ba3" opacity=".8"/>
  <text className="rebar-label-svg" x={x+10} y={Math.max(24,y-10)} fill="#d7a85e">X · Ø{xArm.dia}//{xArm.spacing}</text>
  <text className="rebar-label-svg" x={x+bw-10} y={Math.max(24,y-10)} textAnchor="end" fill="#42d4cd">Y · Ø{yArm.dia}//{yArm.spacing}</text>
  <text x={W/2} y={H-15} textAnchor="middle" fill="#9fb3c8">Malha inferior · X Ø{xArm.dia}//{xArm.spacing} · Y Ø{yArm.dia}//{yArm.spacing}</text>
 </svg></div>
}
