import React,{useMemo,useState} from 'react'
import {collectIntegratedSnapshot,exportStudyJson} from './IntegratedStudyStore'
import {EngineeringBasis, type EngineeringArea} from '../../engineering/EngineeringBasis'

type Area=EngineeringArea
type Status='ok'|'check'|'missing'
type Item={label:string;status:Status;detail:string}
const AREAS:Area[]=['structures','lsf','hydraulics','geotechnics','containment','roads']
const statusLabel=(s:Status)=>s==='ok'?'Calculado / Concluído':s==='check'?'Aprofundar / Verificar':'Dados em falta'
const DATA:Record<Area,{title:string;objective:string;items:Item[]}>= {
 structures:{title:'Estruturas',objective:'Definir sistema resistente, ações, ordem de grandeza das secções e condicionantes ELU/ELS.',items:[{label:'Modelo resistente e geometria',status:'ok',detail:'Definir vãos, apoios, secções, materiais e sistema resistente.'},{label:'Ações e combinações',status:'check',detail:'Confirmar G, Q, vento, neve, sismo e combinações/Anexo Nacional aplicáveis.'},{label:'ELU — resistência e estabilidade',status:'check',detail:'Dimensionar elementos e verificar estabilidade global/local.'},{label:'ELS — deformação e fendilhação',status:'check',detail:'Verificar limites adequados à utilização e elementos não estruturais.'},{label:'Pormenorização e durabilidade',status:'check',detail:'Recobrimentos, ancoragens, emendas, disposições construtivas e exposição.'}]},
 lsf:{title:'Estruturas LSF',objective:'Selecionar modulação/perfis e identificar criticidades de resistência, estabilidade, ligações e contraventamento.',items:[{label:'Modulação e caminho de cargas',status:'ok',detail:'Montantes, guias, pisos/cobertura, vãos e transferência de ações.'},{label:'Secções efetivas',status:'check',detail:'Verificação ativa: confirmar redução por encurvadura local dos elementos de chapa fina.'},{label:'Instabilidade distorcional/global',status:'check',detail:'Verificar modos relevantes do perfil enformado a frio.'},{label:'Diafragmas e contraventamento',status:'check',detail:'Verificação ativa: modelar/confirmar placas, fitas, blocking e estabilidade lateral.'},{label:'Ligações e ancoragens',status:'check',detail:'Parafusos, pull-out/pull-over, esmagamento, rasgamento e uplift.'}]},
 geotechnics:{title:'Geotecnia',objective:'Construir um modelo geotécnico preliminar e verificar viabilidade de fundações, deformações, água e estabilidade.',items:[{label:'Modelo geológico-geotécnico',status:'check',detail:'Estratigrafia, nível freático, parâmetros característicos e variabilidade.'},{label:'Reconhecimento e ensaios',status:'check',detail:'SPT/CPT/CPTu e ensaios laboratoriais adequados ao problema.'},{label:'Capacidade resistente',status:'check',detail:'Verificações geotécnicas coerentes com a abordagem de projeto adotada.'},{label:'Assentamentos / deformações',status:'check',detail:'Avaliar total, diferencial e compatibilidade com a estrutura.'},{label:'Água e estabilidade global',status:'check',detail:'Considerar pressões intersticiais, drenagem e mecanismos globais.'}]},
 containment:{title:'Contenção e estabilização',objective:'Comparar soluções, identificar mecanismos condicionantes e estabelecer geometria/medidas de drenagem preliminares.',items:[{label:'Impulsos e água',status:'check',detail:'Estados ativo/repouso/passivo, sobrecargas e pressões de água.'},{label:'Deslizamento / derrubamento / capacidade',status:'check',detail:'Verificações externas do sistema de contenção.'},{label:'Estabilidade global',status:'check',detail:'Verificação ativa através do módulo Taludes e Estabilidade Global; confirmar superfícies críticas e parâmetros geotécnicos.'},{label:'Resistência estrutural',status:'check',detail:'Muro, perfis, pregagens, ancoragens e revestimentos.'},{label:'Drenagem e construtibilidade',status:'check',detail:'Barbacãs/drenos, faseamento, acessos e condicionantes de execução.'}]},
 hydraulics:{title:'Hidráulica e drenagem',objective:'Definir traçado e pré-dimensionar redes/órgãos verificando caudais, capacidade, pressões, velocidades e cotas.',items:[{label:'Caudais de projeto',status:'check',detail:'Consumos/UD, pluviais e residuais conforme sistema e âmbito.'},{label:'Diâmetros, velocidades e pressões',status:'check',detail:'Verificar intervalos regulamentares e perdas de carga.'},{label:'Pendentes e capacidade de coletores',status:'check',detail:'Avaliar escoamento gravítico, autolimpeza e enchimento.'},{label:'Órgãos e acessibilidade',status:'check',detail:'Válvulas, caixas, câmaras, ventilação, limpeza e manutenção.'},{label:'Traçado e interferências',status:'check',detail:'Verificação ativa de coordenação: confirmar cotas, cruzamentos, recobrimentos e restantes especialidades.'}]},
 roads:{title:'Infraestruturas viárias',objective:'Estabelecer solução geométrica preliminar, terraplenagens, drenagem, pavimento e condicionantes de segurança.',items:[{label:'Traçado em planta e perfil',status:'check',detail:'Raios, trainéis, concordâncias, coordenação planta/perfil e condicionantes.'},{label:'Visibilidade e segurança',status:'check',detail:'Verificação ativa no módulo viário: confirmar distâncias de visibilidade e pontos singulares.'},{label:'Perfis transversais / terraplenagens',status:'check',detail:'Plataforma, taludes, volumes e balanço preliminar de terras.'},{label:'Drenagem',status:'check',detail:'Caudais, valetas, coletores, aquedutos e pontos de descarga.'},{label:'Pavimento e sinalização',status:'check',detail:'Verificação ativa: pré-dimensionar pavimento e validar solução de sinalização/segurança.'}]}
}
function FinalReport({project,snapshot}:{project:string;snapshot:ReturnType<typeof collectIntegratedSnapshot>}){
 const obs=snapshot.observations; const ok=obs.filter(o=>o.status==='ok').length,check=obs.filter(o=>o.status==='check').length,missing=obs.filter(o=>o.status==='missing').length; const total=Math.max(1,ok+check+missing); const progress=Math.round((ok+.55*check)/total*100);
 const date=new Date(snapshot.generatedAt).toLocaleDateString('pt-PT');
 return <div className="report-sheet"><section className="report-page"><header className="report-header"><div className="report-brand">RJP<small>SMARTSTRUCT</small></div><div className="report-meta"><span><b>Data</b><br/>{date}</span><span><b>Título</b><br/>Estudo Prévio de Engenharia<br/>{project}</span></div><div className="report-doc"><b>Documento</b><br/>EP-{new Date().getFullYear()}-001<br/><b>Fase</b><br/>Estudo Prévio</div></header><div className="report-title"><h1>ESTUDO PRÉVIO DE ENGENHARIA</h1><p>{project}</p></div><div className="report-grid2"><div className="report-box"><h2>RESUMO EXECUTIVO</h2><p>Memória técnica multidisciplinar gerada pelo SmartStruct_RJP a partir dos dados disponíveis nos módulos do projeto.</p><p>Os resultados são preliminares e devem ser confirmados e aprofundados nas fases seguintes, com os dados de base, normas, anexos nacionais e verificações aplicáveis.</p></div><div className="report-box"><h2>IDENTIFICAÇÃO DO ESTUDO</h2><p><b>Projeto:</b> {project}</p><p><b>Fase:</b> Estudo Prévio</p><p><b>Ferramenta:</b> SmartStruct_RJP</p><p><b>Responsável:</b> Técnico autor do projeto</p></div></div><div className="report-section" style={{marginTop:18}}><h2>ÍNDICE DE DESENVOLVIMENTO DO ESTUDO</h2><div className="report-kpis"><div className="report-kpi"><b>{progress}%</b>Índice global</div><div className="report-kpi"><b>{ok}</b>Resultados disponíveis</div><div className="report-kpi"><b>{check+missing}</b>Aprofundar / completar</div></div></div><div className="report-section" style={{marginTop:18}}><h2>BASE TÉCNICA</h2><p className="report-note">Estruturas: EN 1990, EN 1991, EN 1992 e EN 1998 conforme aplicável. LSF: EN 1993, com regras específicas para elementos enformados a frio. Geotecnia: EN 1997. Hidráulica/drenagem: regulamentação e normas aplicáveis ao sistema estudado. A edição normativa e Anexo Nacional devem ser confirmados pelo técnico.</p></div><footer className="report-footer"><span>SmartStruct_RJP · Estudo Prévio de Engenharia</span><span>Página 1</span></footer></section>
 <section className="report-page"><header className="report-header"><div className="report-brand">RJP<small>SMARTSTRUCT</small></div><div className="report-meta"><span><b>Data</b><br/>{date}</span><span><b>Projeto</b><br/>{project}</span></div><div className="report-doc"><b>Fase</b><br/>Estudo Prévio</div></header><div className="report-section" style={{marginTop:18}}><h2>1. SUMÁRIO DAS ESPECIALIDADES</h2><table className="report-table"><thead><tr><th>Especialidade</th><th>Objetivo no estudo prévio</th><th>Estado</th><th>Índice</th></tr></thead><tbody>{AREAS.map(a=>{const d=DATA[a],ao=obs.filter(o=>o.area===a);const aok=ao.filter(o=>o.status==='ok').length,ac=ao.filter(o=>o.status==='check').length,am=ao.filter(o=>o.status==='missing').length,n=Math.max(1,ao.length);const ix=Math.round((aok+.55*ac)/n*100);const st:Status=am?'missing':ac?'check':'ok';return <tr key={a}><td><b>{d.title}</b></td><td>{d.objective}</td><td><span className={'report-status '+st}>{st==='ok'?'✓':st==='check'?'!':'○'}</span> {statusLabel(st)}</td><td>{ix}%</td></tr>})}</tbody></table></div><div className="report-section" style={{marginTop:18}}><h2>2. PRINCIPAIS RESULTADOS DISPONÍVEIS</h2><div className="report-observations">{obs.map(o=><div className="report-observation" key={o.id}><strong>{o.title}</strong>{o.value&&<p><b>{o.value}</b></p>}<small>{o.source}</small><p>{o.detail}</p></div>)}</div></div><div className="report-section" style={{marginTop:18}}><h2>3. SOLUÇÃO · CONDICIONANTES · PRÓXIMA FASE</h2><div className="report-decision"><div><b>Solução</b><p>Consolidar a solução tecnicamente viável com base nos resultados disponíveis.</p></div><div><b>Condicionantes</b><p>Resolver dados em falta e verificações que possam alterar geometria, custo ou construtibilidade.</p></div><div><b>Próxima fase</b><p>Completar verificações regulamentares, compatibilização, pormenorização e validação técnica.</p></div></div></div><p className="report-note">Documento de apoio a estudo prévio/pré-dimensionamento. Não substitui projeto de execução, investigação adequada, peças regulamentares nem a responsabilidade do técnico autor.</p><footer className="report-footer"><span>SmartStruct_RJP · Memória integrada</span><span>Página 2</span></footer></section></div>
}
export default function PreliminaryStudyPage(){
 const[area,setArea]=useState<Area>('structures'); const[project,setProject]=useState('Estudo preliminar SmartStruct');
 const data=DATA[area]; const snapshot=collectIntegratedSnapshot(); const areaObs=snapshot.observations.filter(o=>o.area===area)
 const score=useMemo(()=>Math.round(data.items.reduce((s,i)=>s+(i.status==='ok'?1:i.status==='check'?.55:0),0)/data.items.length*100),[data]);
 const total=useMemo(()=>{const o=snapshot.observations;return{ok:o.filter(x=>x.status==='ok').length,check:o.filter(x=>x.status==='check').length,missing:o.filter(x=>x.status==='missing').length}},[snapshot])
 return <div className="page preliminary-study"><FinalReport project={project} snapshot={snapshot}/><div className="pageTitle"><div><h1>Estudo Prévio</h1><span>Memória técnica multidisciplinar · dados reais dos módulos + lacunas de engenharia</span></div><div className="editor-toolbar"><button onClick={()=>exportStudyJson(snapshot,project)}>Exportar estudo</button><button className="primary" onClick={()=>window.print()}>Imprimir / PDF</button></div></div>
 <section className="panel prelim-cover"><label className="field"><span>Designação do estudo</span><input value={project} onChange={e=>setProject(e.target.value)}/></label><div><small>Nível de desenvolvimento da especialidade</small><b>{score}%</b><progress max="100" value={score}/></div></section>
 <section className="panel study-dashboard"><div><small>Resultados integrados</small><b>{total.ok}</b><span>disponíveis</span></div><div><small>A aprofundar</small><b>{total.check}</b><span>verificações</span></div><div><small>Ligações em falta</small><b>{total.missing}</b><span>módulos/dados</span></div></section>
 <div className="prelim-area-tabs">{(Object.keys(DATA) as Area[]).map(a=><button className={a===area?'active':''} onClick={()=>setArea(a)} key={a}>{DATA[a].title}</button>)}</div>
 <section className="panel"><h2>{data.title} · objetivo do estudo prévio</h2><p>{data.objective}</p>{areaObs.length>0&&<div className="study-evidence">{areaObs.map(o=><article className={o.status} key={o.id}><div><b>{o.title}</b><small>{o.source}</small></div>{o.value&&<strong>{o.value}</strong>}<p>{o.detail}</p></article>)}</div>}</section>
 <EngineeringBasis area={area}/>
 <section className="panel"><h2>{data.title} · conteúdo mínimo</h2><div className="prelim-report-list">{data.items.map((it,i)=><article key={i} className={it.status}><span>{it.status==='ok'?'✓':it.status==='check'?'!':'○'}</span><div><b>{it.label}</b><p>{it.detail}</p></div></article>)}</div></section>
 <section className="panel"><h2>Decisão de engenharia preliminar</h2><div className="study-decision-grid"><div><b>1 · Solução</b><p>Escolher a solução tecnicamente viável com base nos resultados disponíveis e condicionantes do local.</p></div><div><b>2 · Condicionantes</b><p>Resolver primeiro itens ○ e utilizações/estados ! que possam alterar geometria, custo ou construtibilidade.</p></div><div><b>3 · Próxima fase</b><p>Completar dados, edição normativa/Anexo Nacional, verificações regulamentares e compatibilização antes do projeto de execução.</p></div></div><p className="note">O SmartStruct apoia o estudo prévio e pré-dimensionamento. Não substitui projeto, investigação adequada, peças regulamentares nem validação e responsabilidade do técnico autor.</p></section></div>
}
