import React,{useMemo,useState} from 'react'
import {exportBIMJson,loadBIMModel,type BIMElement,type SmartStructBIMModel} from '../../engineering/bim/model'

const typePT:Record<string,string>={beam:'Vigas',column:'Pilares',slab:'Lajes',isolated_footing:'Sapatas',strip_footing:'Sapatas contínuas',raft_foundation:'Ensoleiramento',pile:'Estacas',wall:'Paredes',lsf_member:'LSF',pipe:'Tubagens',manhole:'Caixas de visita',road_element:'Elementos viários'}
const fmt=(n:any,d=2)=>typeof n==='number'?n.toFixed(d):String(n??'—')
export default function BIMModelPage(){
 const[tick,setTick]=useState(0),[show,setShow]=useState<'all'|'structure'|'foundations'|'slabs'>('all'),[rot,setRot]=useState(0)
 const model=useMemo(()=>loadBIMModel(),[tick])
 const elements=useMemo(()=>!model?[]:model.elements.filter(e=>show==='all'||(show==='foundations'?['isolated_footing','strip_footing','raft_foundation','pile'].includes(e.type):show==='slabs'?e.type==='slab':['beam','column'].includes(e.type))),[model,show])
 const counts=useMemo(()=>model?Object.entries(model.elements.reduce<Record<string,number>>((a,e)=>(a[e.type]=(a[e.type]||0)+1,a),{})):[],[model])
 return <div className="module-page bim-page"><div className="module-head"><div><h2>Modelo BIM · Estruturas</h2><p>Modelo informacional 3D interno do SmartStruct. Geometria, materiais e resultados de cálculo ligados ao mesmo elemento.</p></div><div className="bim-actions"><button onClick={()=>setTick(x=>x+1)}>Atualizar</button>{model&&<button className="primary" onClick={()=>exportBIMJson(model)}>Exportar BIM JSON</button>}</div></div>
 {!model?<section className="panel"><h3>Ainda não existe modelo BIM</h3><p>Abra <b>Modelo de Edifício</b>, defina a geometria e use <b>Atualizar modelo BIM</b>. O modelo ficará disponível aqui.</p><p className="note">A V89 cria um modelo 3D conceptual e informacional. Não é ainda IFC e não substitui a análise estrutural tridimensional.</p></section>:<>
 <div className="result-grid"><div className="metric"><span>Elementos</span><b>{model.elements.length}</b></div><div className="metric"><span>Pisos</span><b>{new Set(model.elements.map(e=>e.level).filter(Boolean)).size-1}</b></div><div className="metric"><span>Esquema</span><b>{model.schema}</b></div><div className="metric"><span>Atualizado</span><b>{new Date(model.updatedAt).toLocaleDateString('pt-PT')}</b></div></div>
 <section className="panel bim-view-panel"><div className="bim-view-head"><div><h3>Visualizador estrutural 3D</h3><small>Representação isométrica para coordenação e leitura do modelo.</small></div><div className="bim-filter"><select value={show} onChange={e=>setShow(e.target.value as any)}><option value="all">Todos</option><option value="structure">Vigas + pilares</option><option value="slabs">Lajes</option><option value="foundations">Fundações</option></select><button onClick={()=>setRot(r=>(r+1)%4)}>Rodar vista</button></div></div><BIMSvg elements={elements} rotation={rot}/><div className="bim-legend"><span><i className="lg-column"/> Pilares</span><span><i className="lg-beam"/> Vigas</span><span><i className="lg-slab"/> Lajes</span><span><i className="lg-foot"/> Fundações</span></div></section>
 <div className="work-grid"><section className="panel"><h3>Inventário BIM</h3><div className="bim-inventory">{counts.map(([t,n])=><div key={t}><span>{typePT[t]||t}</span><b>{n}</b></div>)}</div></section><section className="panel"><h3>Informação do modelo</h3><div className="rebar-table"><div><b>Projeto</b><span>{model.project.name}</span></div><div><b>Estado</b><span>Modelo conceptual BIM-ready</span></div><div><b>Interoperabilidade</b><span>JSON SmartStruct; IFC é evolução posterior</span></div></div></section></div>
 <section className="panel"><h3>Objetos e propriedades</h3><div className="bim-object-table"><div className="bim-object-row head"><b>ID</b><b>Tipo</b><b>Nível</b><b>Material</b><b>Geometria principal</b><b>Estado</b></div>{model.elements.slice(0,80).map(e=><ObjectRow key={e.id} e={e}/>)}</div>{model.elements.length>80&&<p className="note">A tabela mostra os primeiros 80 elementos. O ficheiro JSON contém o modelo completo.</p>}</section>
 </>}</div>
}
function ObjectRow({e}:{e:BIMElement}){const g=e.geometry;const dims=e.type==='column'?`${fmt(g.b)}×${fmt(g.h)} m · L ${fmt(g.length)} m`:e.type==='beam'?`${fmt(g.b)}×${fmt(g.h)} m · L ${fmt(g.length)} m`:e.type==='slab'?`${fmt(g.width)}×${fmt(g.depth)}×${fmt(g.thickness)} m`:`${fmt(g.width)}×${fmt(g.depth)}×${fmt(g.height)} m`;return <div className="bim-object-row"><span>{e.id}</span><span>{typePT[e.type]||e.type}</span><span>{e.level||'—'}</span><span>{e.material?.name||'—'}</span><span>{dims}</span><span>{e.calculation?.status==='preliminary'?'Pré-dimensionado':e.calculation?.status==='calculated'?'Calculado':'A verificar'}</span></div>}
function BIMSvg({elements,rotation}:{elements:BIMElement[],rotation:number}){
 const all=elements.length?elements:[];let maxX=1,maxY=1,maxZ=1;all.forEach(e=>{const g=e.geometry;maxX=Math.max(maxX,Number(g.x||0)+Number(g.width||g.length||0));maxY=Math.max(maxY,Number(g.y||0)+Number(g.depth||(g.axis==='Y'?g.length:0)||0));maxZ=Math.max(maxZ,Number(g.z||0)+Number(g.height||g.length||g.thickness||0))})
 const W=900,H=540,scale=Math.min(44,620/Math.max(maxX,maxY,1),390/Math.max(maxZ,1));
 const project=(x:number,y:number,z:number)=>{let X=x,Y=y;if(rotation===1){X=y;Y=maxX-x}else if(rotation===2){X=maxX-x;Y=maxY-y}else if(rotation===3){X=maxY-y;Y=x}return{x:W/2+(X-Y)*scale*.72,y:H-55-z*scale-(X+Y)*scale*.28}}
 const line=(e:BIMElement)=>{const g=e.geometry,x=Number(g.x||0),y=Number(g.y||0),z=Number(g.z||0),L=Number(g.length||0),a=project(x,y,z),b=project(x+(g.axis==='Y'?0:L),y+(g.axis==='Y'?L:0),z);return <line key={e.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className="bim-beam-line"/>}
 const col=(e:BIMElement)=>{const g=e.geometry,a=project(Number(g.x||0),Number(g.y||0),Number(g.z||0)),b=project(Number(g.x||0),Number(g.y||0),Number(g.z||0)+Number(g.length||0));return <line key={e.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className="bim-column-line"/>}
 const poly=(e:BIMElement,cls:string)=>{const g=e.geometry,x=Number(g.x||0),y=Number(g.y||0),z=Number(g.z||0),w=Number(g.width||1),d=Number(g.depth||1);const pts=[[x,y],[x+w,y],[x+w,y+d],[x,y+d]].map(([a,b])=>project(a,b,z)).map(p=>`${p.x},${p.y}`).join(' ');return <polygon key={e.id} points={pts} className={cls}/>}
 return <svg viewBox={`0 0 ${W} ${H}`} className="bim-svg"><defs><pattern id="grid89" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M 24 0 L 0 0 0 24" className="bim-grid-line"/></pattern></defs><rect width={W} height={H} fill="url(#grid89)"/><g>{all.filter(e=>e.type==='isolated_footing').map(e=>poly(e,'bim-foot-poly'))}{all.filter(e=>e.type==='slab').map(e=>poly(e,'bim-slab-poly'))}{all.filter(e=>e.type==='column').map(col)}{all.filter(e=>e.type==='beam').map(line)}</g><text x="22" y="30" className="bim-svg-title">SmartStruct BIM · modelo estrutural conceptual</text></svg>
}
