import React,{useMemo,useState} from 'react'
import {solveFrame2D,type FrameModel} from '../../engineering/core/frame2d'
import {solveColumn} from '../columnsPro/ColumnSolver'
import {isolatedFootingPro} from '../foundationsPro/FoundationsSolver'
const model:FrameModel={nodes:[{id:1,x:0,y:0,fixX:true,fixY:true,fixR:true},{id:2,x:5,y:0,fixX:true,fixY:true,fixR:true},{id:3,x:0,y:3},{id:4,x:5,y:3},{id:5,x:0,y:6},{id:6,x:5,y:6,Fx:15000}],elements:[{id:1,a:1,b:3,E:30e9,A:.12,I:.0016},{id:2,a:2,b:4,E:30e9,A:.12,I:.0016},{id:3,a:3,b:4,E:30e9,A:.15,I:.003,qy:-10000},{id:4,a:3,b:5,E:30e9,A:.12,I:.0016},{id:5,a:4,b:6,E:30e9,A:.12,I:.0016},{id:6,a:5,b:6,E:30e9,A:.15,I:.003,qy:-10000}]}
const F=({l,v,s,u}:{l:string,v:number,s:(n:number)=>void,u?:string})=><label className="field"><span>{l}{u?` (${u})`:''}</span><input type="number" step="any" value={v} onChange={e=>s(+e.target.value)}/></label>
const M=({t,v}:{t:string,v:string})=><div className="metric"><span>{t}</span><b>{v}</b></div>
export default function FrameFoundationPage(){
 const[support,setSupport]=useState(1),[q,setQ]=useState(10),[wind,setWind]=useState(15),[b,setB]=useState(.35),[h,setH]=useState(.45),[FB,setFB]=useState(2.2),[FL,setFL]=useState(2.6),[fh,setFh]=useState(.55),[qadm,setQadm]=useState(250)
 const fm=useMemo(()=>({...model,nodes:model.nodes.map(n=>n.id===6?{...n,Fx:wind*1000}:n),elements:model.elements.map(e=>(e.id===3||e.id===6)?{...e,qy:-q*1000}:e)}),[q,wind])
 const fr=useMemo(()=>solveFrame2D(fm),[fm]),idx=fm.nodes.findIndex(n=>n.id===support),Rx=fr.reactions[3*idx]/1000,Ry=fr.reactions[3*idx+1]/1000,Rm=fr.reactions[3*idx+2]/1000
 const N=Math.max(0,Ry),H=Math.abs(Rx),col=useMemo(()=>solveColumn({N,Mx:Math.abs(Rm),My:0,b,h,L:3,fck:30,fyk:500,E:30,cover:.04,phi:16,k:1,end:'fixed-fixed'}),[N,Rm,b,h])
 const foot=useMemo(()=>isolatedFootingPro({N,Hx:H,Hy:0,Mx:col.Mx2,My:0,B:FB,L:FL,h:fh,cb:b,cl:h,cover:.05,qAllow:qadm,mu:.5,fck:30,fyk:500,phi:12}),[N,H,col.Mx2,FB,FL,fh,b,h,qadm])
 return <div className="module-page"><div className="module-head"><div><h2>Pórtico → Fundação · V61</h2><p>Reações do modelo global passam automaticamente para o pilar e para a sapata selecionada.</p></div></div>
 <div className="work-grid"><section className="panel"><h3>1 · Pórtico</h3><div className="form-grid"><F l="q pisos" u="kN/m" v={q} s={setQ}/><F l="Ação horizontal topo" u="kN" v={wind} s={setWind}/><label className="field"><span>Apoio a dimensionar</span><select value={support} onChange={e=>setSupport(+e.target.value)}><option value="1">Apoio 1 · esquerdo</option><option value="2">Apoio 2 · direito</option></select></label></div><FrameSketch support={support}/></section>
 <section className="panel"><h3>2 · Secções</h3><div className="form-grid"><F l="Pilar b" u="m" v={b} s={setB}/><F l="Pilar h" u="m" v={h} s={setH}/><F l="Sapata B" u="m" v={FB} s={setFB}/><F l="Sapata L" u="m" v={FL} s={setFL}/><F l="Sapata h" u="m" v={fh} s={setFh}/><F l="qadm" u="kPa" v={qadm} s={setQadm}/></div></section></div>
 <section className="panel"><h3>3 · Reação extraída automaticamente</h3><div className="result-grid"><M t="Rx" v={`${Rx.toFixed(2)} kN`}/><M t="Ry → N" v={`${Ry.toFixed(2)} kN`}/><M t="M apoio" v={`${Rm.toFixed(2)} kN·m`}/><M t="Apoio" v={`${support}`}/></div></section>
 <section className="panel"><h3>4 · Pilar</h3><div className="result-grid"><M t="NEd" v={`${N.toFixed(1)} kN`}/><M t="M 1.ª ordem" v={`${Math.abs(Rm).toFixed(1)} kN·m`}/><M t="Amplificação" v={col.amp.toFixed(2)}/><M t="M 2.ª ordem" v={`${col.Mx2.toFixed(1)} kN·m`}/><M t="Armadura prelim." v={`${col.nBars} Ø16`}/></div></section>
 <section className="panel"><h3>5 · Sapata do apoio {support}</h3><div className="result-grid"><M t="q mín." v={`${foot.qmin.toFixed(1)} kPa`}/><M t="q máx." v={`${foot.qmax.toFixed(1)} kPa`}/><M t="Terreno" v={`${(100*foot.bearingUtil).toFixed(0)}%`}/><M t="FS desl." v={foot.slideFS.toFixed(2)}/><M t="FS derrub." v={foot.overturnFS.toFixed(2)}/><M t="Punçoamento" v={foot.punchOK?'OK':'REVER'}/><M t="Armadura X" v={`Ø12 // ${foot.spx} mm`}/><M t="Armadura Y" v={`Ø12 // ${foot.spy} mm`}/><M t="Estado" v={foot.ok?'OK':'REVER'}/></div></section>
 <section className="panel"><div className="flow-line"><b>Pórtico global</b><span>→</span><b>Reação apoio {support}</b><span>→</span><b>Pilar</b><span>→</span><b>2.ª ordem</b><span>→</span><b>Sapata</b></div><p className="note">Integração automática para pré-dimensionamento. O modelo V61 é plano e elástico linear; ações, combinações, 2.ª ordem global, EC2/EC7 e parâmetros geotécnicos devem ser confirmados no projeto.</p></section></div>}
function FrameSketch({support}:{support:number}){return <svg viewBox="0 0 520 360" className="eng-svg"><g stroke="#a9bacd" strokeWidth="8" fill="none"><line x1="120" y1="300" x2="120" y2="70"/><line x1="400" y1="300" x2="400" y2="70"/><line x1="120" y1="185" x2="400" y2="185"/><line x1="120" y1="70" x2="400" y2="70"/></g><rect x="95" y="300" width="50" height="12" fill={support===1?'#2dd4bf':'#60a5fa'}/><rect x="375" y="300" width="50" height="12" fill={support===2?'#2dd4bf':'#60a5fa'}/><line x1="450" y1="70" x2="405" y2="70" stroke="#ef4444" strokeWidth="4"/><polygon points="400,70 414,62 414,78" fill="#ef4444"/><text x="445" y="58" fill="#ef4444">H</text><text x="185" y="45" fill="#f59e0b">q</text><text x="100" y="335" fill="#9fb3c8">1</text><text x="395" y="335" fill="#9fb3c8">2</text></svg>}