import type { ModuleId } from './types'
export interface ModuleItem { id: ModuleId; label: string; group: string; status: 'ready' | 'planned' }
export const modules: ModuleItem[] = [
  { id: 'dashboard', label: 'Início', group: 'Geral', status: 'ready' },
  { id: 'beams', label: 'Vigas', group: 'Análise Estrutural', status: 'ready' },
  { id: 'frames', label: 'Pórticos', group: 'Análise Estrutural', status: 'ready' },
  { id: 'trusses', label: 'Treliças', group: 'Análise Estrutural', status: 'ready' },
  { id: 'combinations', label: 'Combinações', group: 'Análise Estrutural', status: 'ready' },
  { id: 'columns', label: 'Pilares', group: 'Betão Armado', status: 'ready' },
  { id: 'slabs', label: 'Lajes', group: 'Betão Armado', status: 'ready' },
  { id: 'foundations', label: 'Sapatas', group: 'Fundações', status: 'ready' },
  { id: 'integrated', label: 'Estrutura Integrada', group: 'Fundações', status: 'ready' },
  { id: 'framefoundation', label: 'Pórtico → Fundação', group: 'Fundações', status: 'ready' },
  { id: 'buildingmodel', label: 'Modelo de Edifício', group: 'Análise Estrutural', status: 'ready' },
  { id: 'bimmodel', label: 'Modelo BIM', group: 'Análise Estrutural', status: 'ready' },
  { id: 'structuralproject', label: 'Structural Project PRO', group: 'Análise Estrutural', status: 'ready' },
  { id: 'lsf', label: 'Estruturas LSF', group: 'Análise Estrutural', status: 'ready' },
  { id: 'steelstructures', label: 'Estruturas Metálicas', group: 'Análise Estrutural', status: 'ready' },
  { id: 'timber', label: 'Estruturas de Madeira · EC5', group: 'Análise Estrutural', status: 'ready' },
  { id: 'masonry', label: 'Alvenaria Estrutural · EC6', group: 'Análise Estrutural', status: 'ready' },
  { id: 'composite', label: 'Estruturas Mistas · EC4', group: 'Análise Estrutural', status: 'ready' },
  { id: 'seismic', label: 'Sismo e Dinâmica · EC8', group: 'Análise Estrutural', status: 'ready' },
  { id: 'deepfoundations', label: 'Fundações Especiais', group: 'Fundações', status: 'ready' },
  { id: 'globalslopes', label: 'Taludes e Estabilidade Global', group: 'Geotecnia', status: 'ready' },
  { id: 'bridges', label: 'Pontes e Obras de Arte', group: 'Infraestruturas', status: 'ready' },
  { id: 'preliminarystudy', label: 'Estudo Prévio', group: 'Geral', status: 'ready' },
  { id: 'rehabilitation', label: 'Reabilitação · Estruturas e Edifícios', group: 'Reabilitação', status: 'ready' },
  { id: 'walls', label: 'Muro em consola', group: 'Contenção', status: 'ready' },
  { id: 'containment', label: 'Muros e sistemas', group: 'Contenção', status: 'ready' },
  { id: 'soilnails', label: 'Pregagens', group: 'Estabilização', status: 'ready' },
  { id: 'anchors', label: 'Ancoragens', group: 'Estabilização', status: 'ready' },
  { id: 'shotcrete', label: 'Betão projetado', group: 'Estabilização', status: 'ready' },
  { id: 'drainage', label: 'Drenagem de taludes', group: 'Estabilização', status: 'ready' },
  { id: 'geotechnics', label: 'Parâmetros de Solo', group: 'Geotecnia', status: 'ready' },
  { id: 'spt', label: 'SPT', group: 'Geotecnia', status: 'ready' },
  { id: 'cpt', label: 'CPT / CPTu', group: 'Geotecnia', status: 'ready' },
  { id: 'bearing', label: 'Capacidade de Carga', group: 'Geotecnia', status: 'ready' },
  { id: 'settlements', label: 'Assentamentos', group: 'Geotecnia', status: 'ready' },
  { id: 'earthpressure', label: 'Impulsos de terras', group: 'Geotecnia', status: 'ready' },
  { id: 'slopes', label: 'Taludes', group: 'Geotecnia', status: 'ready' },
  { id: 'hydraulics', label: 'Hidráulica e Drenagem', group: 'Infraestruturas', status: 'ready' },
  { id: 'roads', label: 'Infraestruturas Viárias', group: 'Infraestruturas Viárias', status: 'ready' },
  { id: 'library', label: 'Biblioteca Técnica', group: 'Ferramentas', status: 'planned' },
  { id: 'tools', label: 'Ferramentas', group: 'Ferramentas', status: 'planned' },
  { id: 'settings', label: 'Configurações', group: 'Ferramentas', status: 'planned' },
  { id: 'help', label: 'Ajuda · Como operar', group: 'Ferramentas', status: 'ready' },
]
