import { useMemo, useState } from 'react'

function Field({label,value,setValue,unit,step='0.1'}:{label:string,value:number,setValue:(v:number)=>void,unit:string,step?:string}){
  return <label>{label} ({unit})<input type="number" step={step} value={value} onChange={e=>setValue(Number(e.target.value))}/></label>
}
function Metric({name,value,status}:{name:string,value:string,status?:'ok'|'warn'|'bad'}){
  return <div className={`metric ${status?`metric--${status}`:''}`}><span>{name}</span><strong>{value}</strong></div>
}
function Layout({title,sub,sketch,fields,results,note}:{title:string,sub:string,sketch:React.ReactNode,fields:React.ReactNode,results:React.ReactNode,note:string}){
  return <div className="page"><div className="pageTitle"><h1>{title}</h1><span>{sub}</span></div><div className="workspace"><section className="panel editorPanel">{sketch}<div className="formGrid">{fields}</div></section><aside className="panel resultPanel"><div className="panelTitle">Resultados preliminares</div>{results}<p className="note">{note}</p></aside></div></div>
}

export function SoilNailsPage(){
  const [H,setH]=useState(7),[L,setL]=useState(6),[sv,setSv]=useState(1.5),[sh,setSh]=useState(1.5),[d,setD]=useState(25),[fy,setFy]=useState(500),[bond,setBond]=useState(120),[hole,setHole]=useState(100),[incl,setIncl]=useState(15)
  const r=useMemo(()=>{const As=Math.PI*d*d/4;const steel=As*fy/1000;const perim=Math.PI*hole/1000;const bondCap=perim*L*bond;const cap=Math.min(steel,bondCap);const density=1/(sv*sh);const nails=Math.ceil(H/sv)+1;return{As,steel,bondCap,cap,density,nails}},[H,L,sv,sh,d,fy,bond,hole])
  const lines=Array.from({length:Math.min(7,Math.max(2,r.nails))})
  return <Layout title="Pregagens" sub="Solo pregado · capacidade axial e malha" sketch={<svg viewBox="0 0 700 300" className="beamSvg"><polygon points="80,245 260,60 620,60 620,245" className="soilFill"/><line x1="80" y1="245" x2="260" y2="60" className="slopeLine"/>{lines.map((_,i)=>{const y=230-i*28;const x=95+i*27;return <g key={i}><line x1={x} y1={y} x2={x+260} y2={y-70} className="anchorLine"/><circle cx={x} cy={y} r="5" className="nodeDot"/></g>})}<text x="390" y="95">L = {L.toFixed(1)} m · α = {incl.toFixed(0)}°</text></svg>} fields={<><Field label="Altura talude" value={H} setValue={setH} unit="m"/><Field label="Comprimento L" value={L} setValue={setL} unit="m"/><Field label="Esp. vertical" value={sv} setValue={setSv} unit="m"/><Field label="Esp. horizontal" value={sh} setValue={setSh} unit="m"/><Field label="Diâmetro barra" value={d} setValue={setD} unit="mm"/><Field label="fy" value={fy} setValue={setFy} unit="MPa"/><Field label="Aderência τ" value={bond} setValue={setBond} unit="kPa"/><Field label="Furo" value={hole} setValue={setHole} unit="mm"/><Field label="Inclinação" value={incl} setValue={setIncl} unit="°"/></>} results={<><Metric name="Área aço" value={`${r.As.toFixed(0)} mm²`}/><Metric name="Resist. aço" value={`${r.steel.toFixed(0)} kN`}/><Metric name="Resist. aderência" value={`${r.bondCap.toFixed(0)} kN`}/><Metric name="Capacidade indicativa" value={`${r.cap.toFixed(0)} kN`} status={r.cap>100?'ok':'warn'}/><Metric name="Densidade" value={`${r.density.toFixed(2)} preg./m²`}/></>} note="Capacidade axial simplificada pela menor resistência entre aço e aderência. Verificar arrancamento, comprimento ativo/passivo, superfície de rotura, face, drenagem e estabilidade global."/>
}

export function AnchorsPage(){
  const [Td,setTd]=useState(350),[free,setFree]=useState(7),[bondL,setBondL]=useState(5),[hole,setHole]=useState(150),[tau,setTau]=useState(180),[EA,setEA]=useState(190000),[As,setAs]=useState(980)
  const r=useMemo(()=>{const bond=Math.PI*(hole/1000)*bondL*tau;const stress=Td*1000/As;const elong=(Td*1000*free*1000)/(EA*As);const utilBond=Td/Math.max(.1,bond);const utilSteel=stress/Math.max(1,0.9*1770);return{bond,stress,elong,utilBond,utilSteel}},[Td,free,bondL,hole,tau,EA,As])
  return <Layout title="Ancoragens" sub="Tirantes ativos · comprimento livre e selagem" sketch={<svg viewBox="0 0 700 280" className="beamSvg"><rect x="120" y="55" width="36" height="180" className="structFill"/><line x1="156" y1="145" x2="520" y2="90" className="anchorLine"/><polygon points="480,82 570,70 535,112" className="anchorBulb"/><circle cx="156" cy="145" r="10" className="anchorHead"/><text x="280" y="120">L livre {free.toFixed(1)} m</text><text x="475" y="60">L selagem {bondL.toFixed(1)} m</text></svg>} fields={<><Field label="Carga Td" value={Td} setValue={setTd} unit="kN"/><Field label="Compr. livre" value={free} setValue={setFree} unit="m"/><Field label="Compr. selagem" value={bondL} setValue={setBondL} unit="m"/><Field label="Diâmetro bolbo" value={hole} setValue={setHole} unit="mm"/><Field label="Aderência τ" value={tau} setValue={setTau} unit="kPa"/><Field label="Área aço" value={As} setValue={setAs} unit="mm²"/><Field label="E aço" value={EA} setValue={setEA} unit="MPa"/></>} results={<><Metric name="Resist. selagem" value={`${r.bond.toFixed(0)} kN`} status={r.utilBond<=.8?'ok':r.utilBond<=1?'warn':'bad'}/><Metric name="Tensão aço" value={`${r.stress.toFixed(0)} MPa`}/><Metric name="Alongamento elástico" value={`${r.elong.toFixed(1)} mm`}/><Metric name="Util. selagem" value={`${(100*r.utilBond).toFixed(0)} %`}/><Metric name="Util. aço indic." value={`${(100*r.utilSteel).toFixed(0)} %`}/></>} note="Cálculo preliminar. Ensaios, carga de bloqueio, perdas, fluência, proteção anticorrosiva, zona livre e selagem devem seguir a solução e especificação adotadas."/>
}

export function ShotcretePage(){
  const [area,setArea]=useState(180),[t,setT]=useState(.10),[waste,setWaste]=useState(12),[fibres,setFibres]=useState(35),[mesh,setMesh]=useState(0)
  const r=useMemo(()=>{const net=area*t;const gross=net*(1+waste/100);const fibre=gross*fibres;const meshMass=area*mesh;return{net,gross,fibre,meshMass}},[area,t,waste,fibres,mesh])
  return <Layout title="Betão projetado" sub="Quantidades · espessura · fibras/malha" sketch={<svg viewBox="0 0 700 260" className="beamSvg"><polygon points="90,225 250,55 620,55 620,225" className="soilFill"/><line x1="90" y1="225" x2="250" y2="55" className="slopeLine thick"/><line x1="104" y1="225" x2="264" y2="55" className="shotcreteLine"/><text x="285" y="92">e = {(t*100).toFixed(0)} cm</text></svg>} fields={<><Field label="Área" value={area} setValue={setArea} unit="m²"/><Field label="Espessura" value={t} setValue={setT} unit="m" step="0.01"/><Field label="Desperdício" value={waste} setValue={setWaste} unit="%"/><Field label="Dosagem fibras" value={fibres} setValue={setFibres} unit="kg/m³"/><Field label="Malha" value={mesh} setValue={setMesh} unit="kg/m²"/></>} results={<><Metric name="Volume líquido" value={`${r.net.toFixed(1)} m³`}/><Metric name="Volume c/ perdas" value={`${r.gross.toFixed(1)} m³`}/><Metric name="Fibras" value={`${r.fibre.toFixed(0)} kg`}/><Metric name="Malha" value={`${r.meshMass.toFixed(0)} kg`}/></>} note="Módulo de quantidades e pré-dimensionamento. A espessura resistente, armadura/fibras, aderência ao suporte e ações locais exigem verificação estrutural específica."/>
}

export function DrainageSystemsPage(){
  const [H,setH]=useState(8),[spacing,setSpacing]=useState(3),[L,setL]=useState(12),[q,setQ]=useState(.12),[width,setWidth]=useState(25)
  const r=useMemo(()=>{const rows=Math.ceil(H/spacing);const per100=Math.ceil(100/spacing)*rows;const totalLen=per100*L;const Q=per100*q;const density=per100/(100*H);return{rows,per100,totalLen,Q,density}},[H,spacing,L,q])
  return <Layout title="Drenagem de taludes" sub="Drenos sub-horizontais e máscara drenante" sketch={<svg viewBox="0 0 700 280" className="beamSvg"><polygon points="70,240 240,55 620,55 620,240" className="soilFill"/><line x1="70" y1="240" x2="240" y2="55" className="slopeLine"/>{[0,1,2].map(i=><line key={i} x1={105+i*48} y1={210-i*52} x2={420+i*15} y2={195-i*52} className="drainLine"/>)}<line x1="82" y1="238" x2="252" y2="53" className="drainMask"/><text x="300" y="85">L dreno = {L.toFixed(1)} m</text></svg>} fields={<><Field label="Altura H" value={H} setValue={setH} unit="m"/><Field label="Espaçamento" value={spacing} setValue={setSpacing} unit="m"/><Field label="Compr. dreno" value={L} setValue={setL} unit="m"/><Field label="Caudal unitário" value={q} setValue={setQ} unit="L/s" step="0.01"/><Field label="Extensão frente" value={width} setValue={setWidth} unit="m"/></>} results={<><Metric name="Níveis" value={`${r.rows}`}/><Metric name="Drenos / 100 m" value={`${r.per100}`}/><Metric name="Comp. total / 100 m" value={`${r.totalLen.toFixed(0)} m`}/><Metric name="Caudal / 100 m" value={`${r.Q.toFixed(1)} L/s`}/><Metric name="Densidade" value={`${r.density.toFixed(3)} dr/m²`}/></>} note="Estimativa geométrica. O espaçamento e comprimento devem resultar da hidrogeologia, superfície de rotura, permeabilidade e resposta piezométrica observada."/>
}
