import React,{useMemo,useState} from 'react'
import {solveColumn,type EndCondition} from '../columnsPro/ColumnSolver'
import {isolatedFootingPro} from '../foundationsPro/FoundationsSolver'
const F=({l,v,s,u}:{l:string,v:number,s:(n:number)=>void,u?:string})=><label className="field"><span>{l}{u?` (${u})`:''}</span><input type="number" step="any" value={v} onChange={e=>s(+e.target.value)}/></label>
const M=({t,v}:{t:string,v:string})=><div className="metric"><span>{t}</span><b>{v}</b></div>
export default function IntegratedStructurePage(){
 const[N,setN]=useState(900),[Mx,setMx]=useState(55),[My,setMy]=useState(20),[Hx,setHx]=useState(35),[Hy,setHy]=useState(0)
 const[b,setB]=useState(.35),[hc,setHc]=useState(.45),[Lc,setLc]=useState(3),[fck,setFck]=useState(30),[fyk,setFyk]=useState(500),[E,setE]=useState(30),[cover,setCover]=useState(.04),[phiC,setPhiC]=useState(16),[end,setEnd]=useState<EndCondition>('pinned')
 const[FB,setFB]=useState(2.2),[FL,setFL]=useState(2.6),[fh,setFh]=useState(.55),[qAllow,setQ]=useState(250),[mu,setMu]=useState(.5),[phiF,setPhiF]=useState(12)
 const col=useMemo(()=>solveColumn({N,Mx,My,b,h:hc,L:Lc,fck,fyk,E,cover,phi:phiC,k:1,end}),[N,Mx,My,b,hc,Lc,fck,fyk,E,cover,phiC,end])
 const foot=useMemo(()=>isolatedFootingPro({N,Hx,Hy,Mx:col.Mx2,My:col.My2,B:FB,L:FL,h:fh,cb:b,cl:hc,cover,qAllow,mu,fck,fyk,phi:phiF}),[N,Hx,Hy,col.Mx2,col.My2,FB,FL,fh,b,hc,cover,qAllow,mu,fck,fyk,phiF])
 return <div className="module-page"><div className="module-head"><div><h2>Estrutura Integrada · V60</h2><p>Pilar → efeitos de 2.ª ordem → esforços transmitidos → sapata isolada.</p></div></div>
 <div className="work-grid"><section className="panel"><h3>1 · Esforços de entrada</h3><div className="form-grid"><F l="NEd" u="kN" v={N} s={setN}/><F l="Mx" u="kN·m" v={Mx} s={setMx}/><F l="My" u="kN·m" v={My} s={setMy}/><F l="Hx" u="kN" v={Hx} s={setHx}/><F l="Hy" u="kN" v={Hy} s={setHy}/></div><h3>Pilar</h3><div className="form-grid"><F l="b" u="m" v={b} s={setB}/><F l="h" u="m" v={hc} s={setHc}/><F l="L" u="m" v={Lc} s={setLc}/><F l="fck" u="MPa" v={fck} s={setFck}/><F l="fyk" u="MPa" v={fyk} s={setFyk}/><F l="E" u="GPa" v={E} s={setE}/><F l="Ø pilar" u="mm" v={phiC} s={setPhiC}/><label className="field"><span>Extremidades</span><select value={end} onChange={e=>setEnd(e.target.value as EndCondition)}><option value="pinned">Art.-Art.</option><option value="fixed-pinned">Enc.-Art.</option><option value="fixed-fixed">Bi-encastrado</option><option value="cantilever">Consola</option></select></label></div></section>
 <section className="panel"><h3>2 · Sapata</h3><div className="form-grid"><F l="B" u="m" v={FB} s={setFB}/><F l="L" u="m" v={FL} s={setFL}/><F l="h" u="m" v={fh} s={setFh}/><F l="qadm" u="kPa" v={qAllow} s={setQ}/><F l="μ" v={mu} s={setMu}/><F l="Recobrimento" u="m" v={cover} s={setCover}/><F l="Ø sapata" u="mm" v={phiF} s={setPhiF}/></div><SystemSvg/></section></div>
 <section className="panel"><h3>3 · Pilar calculado</h3><div className="result-grid"><M t="λx" v={col.lambdaX.toFixed(1)}/><M t="λy" v={col.lambdaY.toFixed(1)}/><M t="Amplificação" v={col.amp.toFixed(2)}/><M t="Mx → sapata" v={`${col.Mx2.toFixed(1)} kN·m`}/><M t="My → sapata" v={`${col.My2.toFixed(1)} kN·m`}/><M t="Armadura pilar" v={`${col.nBars} Ø${phiC}`}/></div></section>
 <section className="panel"><h3>4 · Fundação resultante</h3><div className="result-grid"><M t="q mín." v={`${foot.qmin.toFixed(1)} kPa`}/><M t="q máx." v={`${foot.qmax.toFixed(1)} kPa`}/><M t="Util. terreno" v={`${(foot.bearingUtil*100).toFixed(0)}%`}/><M t="FS deslizamento" v={foot.slideFS.toFixed(2)}/><M t="FS derrubamento" v={foot.overturnFS.toFixed(2)}/><M t="Punçoamento" v={foot.punchOK?'OK':'REVER'}/><M t="Armadura X" v={`Ø${phiF} // ${foot.spx} mm`}/><M t="Armadura Y" v={`Ø${phiF} // ${foot.spy} mm`}/><M t="Estado" v={foot.ok?'OK':'REVER'}/></div></section>
 <section className="panel"><h3>Fluxo de cálculo</h3><div className="flow-line"><b>Ações</b><span>→</span><b>Pilar</b><span>→</span><b>2.ª ordem</b><span>→</span><b>N + H + M</b><span>→</span><b>Sapata</b><span>→</span><b>Terreno + EC2/EC7</b></div><p className="note">V60 cria a primeira cadeia estrutural integrada. O fluxo ainda é de pré-dimensionamento: não substitui combinações regulamentares completas, análise global, estudo geotécnico nem projeto de execução.</p></section></div>}
function SystemSvg(){return <svg viewBox="0 0 500 310" className="eng-svg"><rect x="222" y="35" width="56" height="145" fill="#7890a8"/><rect x="130" y="180" width="240" height="58" fill="#4b6178" stroke="#9fb3c8" strokeWidth="3"/><line x1="250" y1="15" x2="250" y2="65" stroke="#ef4444" strokeWidth="4"/><polygon points="250,75 242,60 258,60" fill="#ef4444"/><line x1="65" y1="108" x2="215" y2="108" stroke="#f59e0b" strokeWidth="4"/><polygon points="220,108 205,100 205,116" fill="#f59e0b"/><path d="M305 85 C350 75 350 135 305 125" fill="none" stroke="#a78bfa" strokeWidth="4"/><text x="262" y="28" fill="#ef4444">N</text><text x="72" y="96" fill="#f59e0b">H</text><text x="350" y="108" fill="#a78bfa">M</text><text x="190" y="270" fill="#9fb3c8">Pilar → Sapata → Terreno</text></svg>}