import React,{useMemo,useState} from 'react'
import {solveTruss,type TrussType} from './TrussSolver'
import {fmt} from '../../engineering/structuralMath'
const F=({l,v,s,u}:{l:string,v:number,s:(n:number)=>void,u?:string})=><label className="field"><span>{l}{u?` (${u})`:''}</span><input type="number" step="any" value={v} onChange={e=>s(+e.target.value)}/></label>
export default function TrussesProPage(){
 const[type,setType]=useState<TrussType>('pratt'),[L,setL]=useState(12),[H,setH]=useState(2.5),[panels,setPanels]=useState(6),[P,setP]=useState(25),[A,setA]=useState(.003),[E,setE]=useState(200),[fy,setFy]=useState(355),[scale,setScale]=useState(80)
 const solved=useMemo(()=>{try{return{r:solveTruss({L,H,panels,P,type,A,E,fy}),error:''}}catch(e){return{r:null,error:e instanceof Error?e.message:String(e)}}},[L,H,panels,P,type,A,E,fy])
 return <div className="module-page"><div className="module-head"><div><h2>Treliças PRO · V58</h2><p>Solver matricial axial · Pratt, Howe e Warren · tração/compressão · tensões e deformada.</p></div></div>
 <div className="tabs-row">{(['pratt','howe','warren'] as TrussType[]).map(x=><button className={type===x?'active':''} onClick={()=>setType(x)} key={x}>{x.toUpperCase()}</button>)}</div>
 <div className="work-grid"><section className="panel"><h3>Geometria / ações</h3><div className="form-grid"><F l="Vão" u="m" v={L} s={setL}/><F l="Altura" u="m" v={H} s={setH}/><F l="Painéis" v={panels} s={setPanels}/><F l="Carga por nó inferior" u="kN" v={P} s={setP}/><F l="Área barra" u="m²" v={A} s={setA}/><F l="E" u="GPa" v={E} s={setE}/><F l="fy" u="MPa" v={fy} s={setFy}/></div><label className="deform-scale">Escala deformada <input type="range" min="1" max="300" value={scale} onChange={e=>setScale(+e.target.value)}/><b>{scale}×</b></label></section>
 <section className="panel"><h3>Modelo / deformada</h3>{solved.r&&<TrussSvg r={solved.r} scale={scale}/>} {solved.error&&<div className="solver-error">{solved.error}</div>}</section></div>
 {solved.r&&<><div className="result-grid"><M t="Rx A" v={`${fmt(solved.r.R[0]/1000)} kN`}/><M t="Ry A" v={`${fmt(solved.r.R[1]/1000)} kN`}/><M t="Ry B" v={`${fmt(solved.r.R[2*solved.r.n+1]/1000)} kN`}/><M t="N tração máx." v={`${fmt(solved.r.maxT)} kN`}/><M t="N compressão máx." v={`${fmt(solved.r.maxC)} kN`}/><M t="Desloc. máx." v={`${fmt(solved.r.maxDisp*1000,2)} mm`}/></div>
 <section className="panel"><h3>Barras</h3><div className="member-table">{solved.r.results.map(e=><div key={e.id}><b>Barra {e.id}</b><span>{e.kind}</span><span>N {fmt(e.N)} kN</span><span>σ {fmt(e.stress)} MPa</span><span>L {fmt(e.L)} m</span><span>Util. tensão {(100*e.util).toFixed(1)}%</span></div>)}</div></section>
 <section className="panel"><p className="note">A V58 resolve a treliça como sistema axial elástico linear. A utilização apresentada compara |σ| com fy e não substitui verificações de encurvadura, classe de secção, ligações e dimensionamento regulamentar completo de barras comprimidas.</p></section></>}</div>}
const M=({t,v}:{t:string,v:string})=><div className="metric"><span>{t}</span><b>{v}</b></div>
function TrussSvg({r,scale}:{r:any,scale:number}){const W=650,H=330,p=55,maxX=Math.max(...r.nodes.map((n:any)=>n.x),1),maxY=Math.max(...r.nodes.map((n:any)=>n.y),1),S=Math.min((W-2*p)/maxX,(H-2*p)/Math.max(maxY,1)),P=(n:any)=>({x:p+n.x*S,y:H-p-n.y*S}),Pd=(n:any,k:number)=>({x:p+(n.x+r.u[2*k]*scale)*S,y:H-p-(n.y+r.u[2*k+1]*scale)*S})
 return <svg viewBox={`0 0 ${W} ${H}`} className="eng-svg">{r.bars.map((e:any)=>{const a=r.nodes.find((n:any)=>n.id===e.a),b=r.nodes.find((n:any)=>n.id===e.b),pa=P(a),pb=P(b),res=r.results.find((x:any)=>x.id===e.id),stroke=res.kind==='Tração'?'#38bdf8':res.kind==='Compressão'?'#ef6b6b':'#9fb3c8';return <line key={e.id} x1={pa.x} y1={pa.y} x2={pb.x} y2={pb.y} stroke={stroke} strokeWidth="4"/>})}{r.bars.map((e:any)=>{const ia=r.nodes.findIndex((n:any)=>n.id===e.a),ib=r.nodes.findIndex((n:any)=>n.id===e.b),a=Pd(r.nodes[ia],ia),b=Pd(r.nodes[ib],ib);return <line key={'d'+e.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="#f59e0b" strokeWidth="2" strokeDasharray="7 5"/>})}{r.nodes.map((n:any,k:number)=>{const q=P(n);return <g key={n.id}><circle cx={q.x} cy={q.y} r="5" fill="#e7eef6"/><text x={q.x+6} y={q.y-7} fill="#8fa5bf" fontSize="10">{n.id}</text></g>})}<text x="20" y="22" fill="#38bdf8" fontSize="12">Azul: tração</text><text x="120" y="22" fill="#ef6b6b" fontSize="12">Vermelho: compressão</text><text x="285" y="22" fill="#f59e0b" fontSize="12">tracejado: deformada</text></svg>}