import React,{useState} from 'react'
import {EngineeringBasis,PreliminaryChecklist} from '../../engineering/EngineeringBasis'
const N=({l,v,s,u}:{l:string;v:number;s:(n:number)=>void;u?:string})=><label className="field"><span>{l}{u?` (${u})`:''}</span><input type="number" step="any" value={v} onChange={e=>s(+e.target.value)}/></label>
const R=({l,v,n}:{l:string;v:string;n?:string})=><article className="steel-status-card"><span>{l}</span><b>{v}</b>{n&&<small>{n}</small>}</article>
function Base({title,sub,fields,result,checks}:{title:string;sub:string;fields:React.ReactNode;result:React.ReactNode;checks:string[]}){return <div className="page"><div className="pageTitle"><div><h1>{title}</h1><span>{sub}</span></div></div><div className="work-grid"><section className="panel"><h2>Dados de cálculo</h2><div className="form-grid">{fields}</div></section><section className="panel"><h2>Resultados · triagem</h2><div className="steel-status-grid">{result}</div><p className="note">Pré-dimensionamento. Confirmar modelo, ações, edição normativa e Anexo Nacional antes de projeto final.</p></section></div><section className="panel"><h2>Verificações a completar</h2><PreliminaryChecklist items={checks.map((x,i)=>({name:x,status:i<2?'check' as const:'missing' as const,detail:i<2?'Triagem implementada.':'Completar no dimensionamento final.'}))}/></section><EngineeringBasis area="structures"/></div>}
export function TimberPage(){const[b,sb]=useState(140),[h,sh]=useState(360),[fm,sfm]=useState(24),[M,sM]=useState(28),[k,sk]=useState(.8),[g,sg]=useState(1.3);const rd=b*h*h/6*k*fm/g/1e6;return <Base title="Estruturas de Madeira · EC5" sub="V103 · madeira maciça e lamelada" fields={<><N l="b" u="mm" v={b} s={sb}/><N l="h" u="mm" v={h} s={sh}/><N l="fm,k" u="MPa" v={fm} s={sfm}/><N l="kmod" v={k} s={sk}/><N l="γM" v={g} s={sg}/><N l="MEd" u="kN·m" v={M} s={sM}/></>} result={<><R l="MRd" v={`${rd.toFixed(1)} kN·m`}/><R l="ηM" v={(M/rd).toFixed(2)}/></>} checks={['Flexão','Classes de serviço / kmod','Corte','Compressão / tração','Encurvadura','ELS e ligações']}/>}
export function MasonryPage(){const[t,st]=useState(200),[L,sL]=useState(3),[fk,sfk]=useState(5),[Ned,sN]=useState(180),[g,sg]=useState(2);const rd=fk/g*t*L;return <Base title="Alvenaria Estrutural · EC6" sub="V104 · paredes resistentes" fields={<><N l="Espessura" u="mm" v={t} s={st}/><N l="Comprimento" u="m" v={L} s={sL}/><N l="fk" u="MPa" v={fk} s={sfk}/><N l="γM" v={g} s={sg}/><N l="NEd" u="kN" v={Ned} s={sN}/></>} result={<><R l="NRd bruto" v={`${rd.toFixed(0)} kN`}/><R l="η" v={(Ned/rd).toFixed(2)}/></>} checks={['Compressão','Esbelteza','Corte','Ações laterais','Amarrações']}/>}
export function CompositePage(){const[W,sW]=useState(900),[fy,sfy]=useState(355),[M,sM]=useState(250),[boost,sb]=useState(1.35);const steel=W*1000*fy/1e6,rd=steel*boost;return <Base title="Estruturas Mistas Aço–Betão · EC4" sub="V105 · colaboração aço–betão" fields={<><N l="W aço" u="cm³" v={W} s={sW}/><N l="fy" u="MPa" v={fy} s={sfy}/><N l="Fator colaboração indicativo" v={boost} s={sb}/><N l="MEd" u="kN·m" v={M} s={sM}/></>} result={<><R l="MRd indicativo" v={`${rd.toFixed(0)} kN·m`}/><R l="η" v={(M/rd).toFixed(2)}/></>} checks={['Secção mista','Grau de conexão','Conectores','Fase construtiva','ELS / vibração']}/>}
export function SeismicPage(){const[m,sm]=useState(1200),[ag,sa]=useState(.15),[q,sq]=useState(3),[S,sS]=useState(1.2);const F=m*9.81*ag*S/q;return <Base title="Sismo e Dinâmica · EC8" sub="V106 · ações sísmicas e dinâmica" fields={<><N l="Massa sísmica" u="t" v={m} s={sm}/><N l="ag/g" v={ag} s={sa}/><N l="S" v={S} s={sS}/><N l="q" v={q} s={sq}/></>} result={<R l="Fb indicativo" v={`${F.toFixed(0)} kN`} n="força basal simplificada"/>} checks={['Força basal','Distribuição por pisos','Espectro','Modos / massas','Torção / irregularidade','Combinações']}/>}
export function DeepFoundationsPage(){const[d,sd]=useState(.6),[L,sL]=useState(15),[qb,sq]=useState(2500),[fs,sf]=useState(55),[N,sN]=useState(1200),[g,sg]=useState(1.4);const R=(Math.PI*d*d/4*qb+Math.PI*d*L*fs)/g;return <Base title="Fundações Especiais" sub="V107 · estacas e microestacas" fields={<><N l="Diâmetro" u="m" v={d} s={sd}/><N l="Comprimento" u="m" v={L} s={sL}/><N l="qb" u="kPa" v={qb} s={sq}/><N l="fs" u="kPa" v={fs} s={sf}/><N l="γR" v={g} s={sg}/><N l="NEd" u="kN" v={N} s={sN}/></>} result={<><R l="Rd axial" v={`${R.toFixed(0)} kN`}/><R l="η" v={(N/R).toFixed(2)}/></>} checks={['Ponta + fuste','Resistência axial','Grupo','Assentamentos','Maciço','Ações horizontais']}/>}
export function GlobalSlopesPage(){const[c,sc]=useState(18),[phi,sp]=useState(28),[W,sW]=useState(900),[a,sa]=useState(24),[u,su]=useState(45),[L,sL]=useState(18);const r=(x:number)=>x*Math.PI/180,FS=(c*L+(W*Math.cos(r(a))-u*L)*Math.tan(r(phi)))/(W*Math.sin(r(a)));return <Base title="Taludes e Estabilidade Global" sub="V108 · equilíbrio limite" fields={<><N l="c'" u="kPa" v={c} s={sc}/><N l="φ'" u="°" v={phi} s={sp}/><N l="W" u="kN" v={W} s={sW}/><N l="α" u="°" v={a} s={sa}/><N l="u" u="kPa" v={u} s={su}/><N l="L" u="m" v={L} s={sL}/></>} result={<R l="FS plano" v={FS.toFixed(2)}/>} checks={['Equilíbrio limite','Água / pressão neutra','Superfície crítica','Bishop / Janbu','Morgenstern-Price','Reforços']}/>}
export function BridgesPage(){const[L,sL]=useState(25),[g,sg]=useState(35),[q,sq]=useState(45),[f,sf]=useState(1.5);const w=g+f*q,M=w*L*L/8,V=w*L/2;return <Base title="Pontes e Obras de Arte" sub="V110 · tabuleiros, encontros, pilares e fundações" fields={<><N l="Vão" u="m" v={L} s={sL}/><N l="gk" u="kN/m" v={g} s={sg}/><N l="qk" u="kN/m" v={q} s={sq}/><N l="Fator tráfego indicativo" v={f} s={sf}/></>} result={<><R l="Mmax" v={`${M.toFixed(0)} kN·m`}/><R l="Vmax" v={`${V.toFixed(0)} kN`}/></>} checks={['Modelo longitudinal','Ações de tráfego','Apoios / juntas','Encontros / pilares','Fundações','Fadiga / durabilidade','Ações ferroviárias']}/>}
