import React,{useMemo,useState} from 'react'
import {solveFrame2D,type FrameModel,type FrameElement,type FrameNode} from '../../engineering/core/frame2d'
type SupportPreset='free'|'pin'|'roller-x'|'roller-y'|'fixed'
const portal:FrameModel={nodes:[{id:1,x:0,y:0,fixX:true,fixY:true,fixR:true},{id:2,x:0,y:3},{id:3,x:5,y:3,Fy:-20000},{id:4,x:5,y:0,fixX:true,fixY:true,fixR:true}],elements:[{id:1,a:1,b:2,E:30e9,A:.12,I:.0016},{id:2,a:2,b:3,E:30e9,A:.15,I:.003,qy:-12000},{id:3,a:3,b:4,E:30e9,A:.12,I:.0016}]}
const oneBayTwoStorey:FrameModel={nodes:[{id:1,x:0,y:0,fixX:true,fixY:true,fixR:true},{id:2,x:5,y:0,fixX:true,fixY:true,fixR:true},{id:3,x:0,y:3},{id:4,x:5,y:3},{id:5,x:0,y:6},{id:6,x:5,y:6,Fx:15000}],elements:[{id:1,a:1,b:3,E:30e9,A:.12,I:.0016},{id:2,a:2,b:4,E:30e9,A:.12,I:.0016},{id:3,a:3,b:4,E:30e9,A:.15,I:.003,qy:-10000},{id:4,a:3,b:5,E:30e9,A:.12,I:.0016},{id:5,a:4,b:6,E:30e9,A:.12,I:.0016},{id:6,a:5,b:6,E:30e9,A:.15,I:.003,qy:-10000}]}
function supportOf(n:FrameNode):SupportPreset{if(n.fixX&&n.fixY&&n.fixR)return'fixed';if(n.fixX&&n.fixY)return'pin';if(n.fixX&&!n.fixY)return'roller-y';if(!n.fixX&&n.fixY)return'roller-x';return'free'}
function applyPreset(n:FrameNode,p:SupportPreset):FrameNode{if(p==='fixed')return{...n,fixX:true,fixY:true,fixR:true};if(p==='pin')return{...n,fixX:true,fixY:true,fixR:false};if(p==='roller-x')return{...n,fixX:false,fixY:true,fixR:false};if(p==='roller-y')return{...n,fixX:true,fixY:false,fixR:false};return{...n,fixX:false,fixY:false,fixR:false}}
const num=(v:number)=>Number.isFinite(v)?v:0
export default function Frame2DProPage(){
 const[model,setModel]=useState<FrameModel>(portal),[selectedNode,setSelectedNode]=useState(3),[selectedElement,setSelectedElement]=useState(2),[scale,setScale]=useState(100)
 const solved=useMemo(()=>{try{return{r:solveFrame2D(model),error:''}}catch(e){return{r:null,error:e instanceof Error?e.message:String(e)}}},[model])
 const node=model.nodes.find(n=>n.id===selectedNode),elem=model.elements.find(e=>e.id===selectedElement)
 const updateNode=(id:number,p:Partial<FrameNode>)=>setModel({...model,nodes:model.nodes.map(n=>n.id===id?{...n,...p}:n)})
 const updateElement=(id:number,p:Partial<FrameElement>)=>setModel({...model,elements:model.elements.map(e=>e.id===id?{...e,...p}:e)})
 function addNode(){const id=Math.max(0,...model.nodes.map(n=>n.id))+1;setModel({...model,nodes:[...model.nodes,{id,x:2.5,y:1.5}]});setSelectedNode(id)}
 function addElement(){if(model.nodes.length<2)return;const id=Math.max(0,...model.elements.map(e=>e.id))+1,a=model.nodes[model.nodes.length-2].id,b=model.nodes[model.nodes.length-1].id;setModel({...model,elements:[...model.elements,{id,a,b,E:30e9,A:.12,I:.0016,qy:0}]});setSelectedElement(id)}
 function delElement(){if(!elem)return;setModel({...model,elements:model.elements.filter(e=>e.id!==elem.id)});setSelectedElement(model.elements.find(e=>e.id!==elem.id)?.id||0)}
 function delNode(){if(!node)return;const connected=model.elements.some(e=>e.a===node.id||e.b===node.id);if(connected)return;setModel({...model,nodes:model.nodes.filter(n=>n.id!==node.id)});setSelectedNode(model.nodes.find(n=>n.id!==node.id)?.id||0)}
 const maxDisp=solved.r?Math.max(...model.nodes.map((_,i)=>Math.hypot(solved.r!.displacements[3*i],solved.r!.displacements[3*i+1]))):0
 const maxM=solved.r?Math.max(...solved.r.endForces.flatMap(e=>[Math.abs(e.M1),Math.abs(e.M2)]))/1000:0
 return <div className="module-page"><div className="module-head"><div><h2>Pórticos 2D PRO · V57</h2><p>Solver matricial 2D · 3 GDL/nó · cargas nodais e distribuídas nas barras · deformada · N/V/M.</p></div></div>
 <div className="editor-toolbar"><button onClick={()=>{setModel(portal);setSelectedNode(3);setSelectedElement(2)}}>Modelo 1 piso</button><button onClick={()=>{setModel(oneBayTwoStorey);setSelectedNode(6);setSelectedElement(6)}}>Modelo 2 pisos</button><button onClick={addNode}>+ Nó</button><button onClick={addElement}>+ Barra</button><button onClick={delElement}>Apagar barra</button><button onClick={delNode}>Apagar nó livre</button><label className="deform-scale">Escala deformada <input type="range" min="1" max="400" value={scale} onChange={e=>setScale(+e.target.value)}/><b>{scale}×</b></label></div>
 <div className="editor-grid"><section className="panel"><FrameSvg model={model} result={solved.r} scale={scale} selectedNode={selectedNode} selectedElement={selectedElement} setNode={setSelectedNode} setElement={setSelectedElement}/></section>
 <section className="panel control-stack"><div><h3>Nó {selectedNode}</h3>{node&&<div className="form-grid"><Field l="x" u="m" v={node.x} s={v=>updateNode(node.id,{x:v})}/><Field l="y" u="m" v={node.y} s={v=>updateNode(node.id,{y:v})}/><Field l="Fx" u="kN" v={(node.Fx||0)/1000} s={v=>updateNode(node.id,{Fx:v*1000})}/><Field l="Fy" u="kN" v={(node.Fy||0)/1000} s={v=>updateNode(node.id,{Fy:v*1000})}/><Field l="M" u="kN·m" v={(node.M||0)/1000} s={v=>updateNode(node.id,{M:v*1000})}/><label className="field"><span>Apoio</span><select value={supportOf(node)} onChange={e=>updateNode(node.id,applyPreset(node,e.target.value as SupportPreset))}><option value="free">Livre</option><option value="pin">Articulado</option><option value="roller-x">Móvel X</option><option value="roller-y">Móvel Y</option><option value="fixed">Encastre</option></select></label></div>}</div>
 <div><h3>Barra {selectedElement}</h3>{elem&&<div className="form-grid"><Field l="Nó inicial" v={elem.a} s={v=>updateElement(elem.id,{a:v})}/><Field l="Nó final" v={elem.b} s={v=>updateElement(elem.id,{b:v})}/><Field l="E" u="GPa" v={elem.E/1e9} s={v=>updateElement(elem.id,{E:v*1e9})}/><Field l="A" u="m²" v={elem.A} s={v=>updateElement(elem.id,{A:v})}/><Field l="I" u="m⁴" v={elem.I} s={v=>updateElement(elem.id,{I:v})}/><Field l="q local y" u="kN/m" v={(elem.qy||0)/1000} s={v=>updateElement(elem.id,{qy:v*1000})}/></div>}</div>{solved.error&&<div className="solver-error">{solved.error}</div>}</section></div>
 {solved.r&&<><div className="result-grid"><Metric t="Nós" v={`${model.nodes.length}`}/><Metric t="Barras" v={`${model.elements.length}`}/><Metric t="Desloc. máx." v={`${(maxDisp*1000).toFixed(3)} mm`}/><Metric t="|M| máx." v={`${maxM.toFixed(2)} kN·m`}/></div>
 <section className="panel"><h3>Deslocamentos nodais</h3><div className="member-table">{model.nodes.map((n,i)=><div key={n.id}><b>Nó {n.id}</b><span>ux {(solved.r!.displacements[3*i]*1000).toFixed(3)} mm</span><span>uy {(solved.r!.displacements[3*i+1]*1000).toFixed(3)} mm</span><span>rz {solved.r!.displacements[3*i+2].toExponential(3)} rad</span></div>)}</div></section>
 <section className="panel"><h3>Reações</h3><div className="member-table">{model.nodes.filter(n=>n.fixX||n.fixY||n.fixR).map(n=>{const i=model.nodes.findIndex(x=>x.id===n.id);return <div key={n.id}><b>Nó {n.id}</b><span>Rx {(solved.r!.reactions[3*i]/1000).toFixed(2)} kN</span><span>Ry {(solved.r!.reactions[3*i+1]/1000).toFixed(2)} kN</span><span>M {(solved.r!.reactions[3*i+2]/1000).toFixed(2)} kN·m</span></div>})}</div></section>
 <section className="panel"><h3>Esforços de extremidade</h3><div className="member-table">{solved.r.endForces.map(e=><div key={e.elementId}><b>Barra {e.elementId}</b><span>N1 {(e.N1/1000).toFixed(2)} · N2 {(e.N2/1000).toFixed(2)} kN</span><span>V1 {(e.V1/1000).toFixed(2)} · V2 {(e.V2/1000).toFixed(2)} kN</span><span>M1 {(e.M1/1000).toFixed(2)} · M2 {(e.M2/1000).toFixed(2)} kN·m</span></div>)}</div></section>
 <section className="diagrams-grid"><section className="panel"><h3>Diagrama N</h3><EndForceDiagram forces={solved.r.endForces} type="N"/></section><section className="panel"><h3>Diagrama V</h3><EndForceDiagram forces={solved.r.endForces} type="V"/></section><section className="panel"><h3>Diagrama M</h3><EndForceDiagram forces={solved.r.endForces} type="M"/></section></section>
 <section className="panel"><p className="note">V57 efetua análise elástica linear de pórticos planos. A carga q atua no eixo local y de cada barra. Dimensionamento regulamentar de secções, combinações, imperfeições e efeitos de 2.ª ordem globais ficam para etapas seguintes.</p></section></>}</div>
}
const Metric=({t,v}:{t:string,v:string})=><div className="metric"><span>{t}</span><b>{v}</b></div>
function Field({l,v,s,u}:{l:string,v:number,s:(n:number)=>void,u?:string}){return <label className="field"><span>{l}{u?` (${u})`:''}</span><input type="number" step="any" value={v} onChange={e=>s(num(+e.target.value))}/></label>}
function FrameSvg({model,result,scale,selectedNode,selectedElement,setNode,setElement}:{model:FrameModel,result:any,scale:number,selectedNode:number,selectedElement:number,setNode:(n:number)=>void,setElement:(n:number)=>void}){
 const W=700,H=440,p=70,minX=Math.min(0,...model.nodes.map(n=>n.x)),maxX=Math.max(1,...model.nodes.map(n=>n.x)),minY=Math.min(0,...model.nodes.map(n=>n.y)),maxY=Math.max(1,...model.nodes.map(n=>n.y)),S=Math.min((W-2*p)/Math.max(maxX-minX,1),(H-2*p)/Math.max(maxY-minY,1))
 const P=(n:FrameNode)=>({x:p+(n.x-minX)*S,y:H-p-(n.y-minY)*S}),Pd=(n:FrameNode,i:number)=>({x:p+(n.x-minX+(result?.displacements[3*i]||0)*scale)*S,y:H-p-(n.y-minY+(result?.displacements[3*i+1]||0)*scale)*S})
 return <svg viewBox={`0 0 ${W} ${H}`} className="eng-svg editor-svg">{model.elements.map(e=>{const na=model.nodes.find(n=>n.id===e.a),nb=model.nodes.find(n=>n.id===e.b);if(!na||!nb)return null;const a=P(na),b=P(nb);return <g key={'u'+e.id} onClick={()=>setElement(e.id)} style={{cursor:'pointer'}}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={selectedElement===e.id?'#2dd4bf':'#a9bacd'} strokeWidth={selectedElement===e.id?9:6}/>{(e.qy||0)!==0&&<text x={(a.x+b.x)/2} y={(a.y+b.y)/2-12} fill="#f59e0b" fontSize="13">q={(e.qy!/1000).toFixed(1)} kN/m</text>}</g>})}
 {result&&model.elements.map(e=>{const ia=model.nodes.findIndex(n=>n.id===e.a),ib=model.nodes.findIndex(n=>n.id===e.b);if(ia<0||ib<0)return null;const a=Pd(model.nodes[ia],ia),b=Pd(model.nodes[ib],ib);return <line key={'d'+e.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke="#f59e0b" strokeWidth="3" strokeDasharray="8 5"/>})}
 {model.nodes.map(n=>{const q=P(n);return <g key={n.id} onClick={()=>setNode(n.id)} style={{cursor:'pointer'}}><Support n={n} x={q.x} y={q.y}/><circle cx={q.x} cy={q.y} r={selectedNode===n.id?10:7} fill={selectedNode===n.id?'#2dd4bf':'#e7eef6'}/><text x={q.x+11} y={q.y-10} fill="#9fb3c8">{n.id}</text>{((n.Fx||0)!==0||(n.Fy||0)!==0)&&<text x={q.x+8} y={q.y+18} fill="#ef4444" fontSize="12">F</text>}</g>})}<text x="20" y="25" fill="#f59e0b" fontSize="13">— — deformada amplificada</text></svg>}
function Support({n,x,y}:{n:FrameNode,x:number,y:number}){if(n.fixX&&n.fixY&&n.fixR)return <rect x={x-16} y={y+7} width="32" height="9" fill="#60a5fa"/>;if(n.fixX&&n.fixY)return <polygon points={`${x},${y+5} ${x-13},${y+27} ${x+13},${y+27}`} fill="#60a5fa"/>;if(!n.fixX&&n.fixY)return <><polygon points={`${x},${y+5} ${x-13},${y+24} ${x+13},${y+24}`} fill="#60a5fa"/><circle cx={x-7} cy={y+30} r="4" fill="#93c5fd"/><circle cx={x+7} cy={y+30} r="4" fill="#93c5fd"/></>;if(n.fixX&&!n.fixY)return <g transform={`rotate(-90 ${x} ${y})`}><polygon points={`${x},${y+5} ${x-13},${y+24} ${x+13},${y+24}`} fill="#60a5fa"/></g>;return null}
function EndForceDiagram({forces,type}:{forces:any[],type:'N'|'V'|'M'}){const W=620,H=210,p=35,vals=forces.flatMap(f=>type==='N'?[f.N1,f.N2]:type==='V'?[f.V1,f.V2]:[f.M1,f.M2]),max=Math.max(1,...vals.map((v:number)=>Math.abs(v)));return <svg viewBox={`0 0 ${W} ${H}`} className="eng-svg"><line x1={p} y1={H/2} x2={W-p} y2={H/2} stroke="#52677c"/>{forces.map((f,i)=>{const x1=p+i*(W-2*p)/Math.max(forces.length,1),x2=p+(i+1)*(W-2*p)/Math.max(forces.length,1),a=type==='N'?f.N1:type==='V'?f.V1:f.M1,b=type==='N'?f.N2:type==='V'?f.V2:f.M2,y1=H/2-a*(H*.35)/max,y2=H/2-b*(H*.35)/max;return <g key={f.elementId}><line x1={x1} y1={y1} x2={x2} y2={y2} stroke={type==='N'?'#22c55e':type==='V'?'#38bdf8':'#a78bfa'} strokeWidth="4"/><text x={(x1+x2)/2-12} y={H-12} fill="#8fa5bf" fontSize="11">B{f.elementId}</text></g>})}</svg>}
